### ISSUE TITLE
Timeout for Notifications and Setup Screen

### ISSUE THREAD

**Issue by e2m32** [thanksmister/android-mqtt-alarm-panel#10]
Hi! Love the app. I am experiencing 2 issues related to what I believe is some kind of timeout. I haven't seen this anywhere and am wondering if this is just related to my device.

I am running the app on an old Galaxy S3, android v4.4 kitkat.

When in the settings I could be entering data and the screen will timeout and return back to the main screen for the alarm panel.

When receiving a MQTT message from 'home/notification', the message does appear, but it times out so fast that if you blink you will miss it. It times out so fast you can't even see what the message was.

Is this just me?

Original Post under wrong project: https://github.com/thanksmister/androidthings-mqtt-alarm-panel/issues/3

**Comment by thanksmister** [comment]
You're screensaver is on either clock or photo and your timeout interval is
set really low.  When the screensaver kicks in it returns you to the main
screen and dismisses any alert dialogs.

Probably need to change this behavior in a future update.  The settings
screen should timeout but be something like 5 minutes always.   Not sure
about clearing dialogs when the screensaver activates. I have to test that
behavior.
