### ISSUE TITLE
not playing audio when providing port inside url

### ISSUE THREAD

**Issue by aaamoeder** [thanksmister/android-mqtt-alarm-panel#102]
So I'm trying to make the alarm completely internet independant and trying to play some audio files from my HA www folder, but since HA is running on port 8123 my files are also served from there..
Using the internal ip and pointing to the mp3 files doesn't work, while I'm sure the links are correct (when copy pasting the links into chrome it plays fine..)

also when I upload the files to an internet host and i paste that url into the action it works fine too, so I'm assuming it's the port inside the local url..

**Comment by thanksmister** [comment]
This does not relate to the application.
