### ISSUE TITLE
Alarm Panel crashing after a couple of reboots

### ISSUE THREAD

**Issue by BoneheadFraggle** [thanksmister/android-mqtt-alarm-panel#103]
**Describe the bug**
Alarm Panel crashes at start. Reboots doesn't help.

**To Reproduce**
After a couple of reboots, Alarm Panel no longer starts. I have only experienced this on my Sony Xperia Performance X phone, but there it is reproducable. The number of restarts vary from 1-3 so far.

**Expected behavior**
I excpect a normal start after reboot.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Sony Xperia Performance X
 - OS: Android 8.0.0

**Additional context**
The problem remains if I clear the app cache.
The problem disappears after clearing all app data, the the app start again, and I need no configure it from the beginning again.
So I guess it has something to do with corrupted app data.

**Comment by thanksmister** [comment]
I don't see any crash reports for a Sony device for the current version of the application.  You didn't mention which version of the application you are using.
