### ISSUE TITLE
Doorbell camera view on ring (intercom- esque)

### ISSUE THREAD

**Issue by jaburges** [thanksmister/android-mqtt-alarm-panel#106]
**Is your feature request related to a problem? Please describe.**
First of all thanks for building this and have a feature request! Panel's are ordered and looking forward to testing!
**Describe the solution you'd like**
I've been looking for the right Alarm panel (mostly for the more elderly guests) as the wink relays I have, the screen is too small. I'm going to set up 2 or maybe 3 panels in suitable locations. 

Ideally when someone rings the doorbell, the alert is sent to HA. (I use node-red) an automation is then started to stream camera.doorbell to all the panels. 
There are of course many different doorbells, but it seems the most common solution for this is to stream the camera in HA. So in my (non dev mind) I would then send an MQTT message to wall panels (like your existing alert) to display the camera for 45 seconds and then return to the alarm panel. 

**Describe alternatives you've considered**
Some are cloud based doorbells, few are locally based (although seem to be increasing given their preference in the community) Alternatively would it be possible to hand off to the Doorbell application to use the full functionality? ie Ring, Yale, Nest and so on. There would be more of a lag than simply streaming the camera from HA for the user to see and make a decision. 
The app hand off would also allow 2 way communication, allowing the panel viewer to talk to the person at the doorbell.

Another alternative would be to add the rtsp stream of the camera in question to the settings of your app, and then on a specific MQTT alert message, bring the camera to the foreground for 45seconds (i imagine others would want different timing, so maybe that would be a setting also?).

**Additional context**
A final thanks for your efforts :)

**Comment by thanksmister** [comment]
The application cannot display streams, the software for showing streams on Android only supports MJPEG streams, not RTSP streams.   There just isn't support for this functionality and I have no plans on integrating this into the application.

**Comment by jaburges** [comment]
ok, thanks for the info
