### ISSUE TITLE
lovelace custom: cards dont load

### ISSUE THREAD

**Issue by jaburges** [thanksmister/android-mqtt-alarm-panel#107]
**Describe the bug**
Lovelace Home Assistant custom:cards are not loading
claims `custom element doesn't exist`

**To Reproduce**
load any lovelace page with custom cards
**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
Huawei android tablet

**Additional context**

**Comment by thanksmister** [comment]
There is no fix for issues rendering web pages with the application.  The application's ability to render web pages is based on the version of the Android on the device.

**Comment by jaburges** [comment]
thanks for the rapid response - good to know
