### ISSUE TITLE
Fingerprint Unlock feature disappeared in the v0.8.7

### ISSUE THREAD

**Issue by giuseppeg88** [thanksmister/android-mqtt-alarm-panel#111]
**Describe the bug**
In the app v8.7.0 (currently the last one) the option to enable the "Fingerprint Unlock" feature is no longer present.

**Smartphone (please complete the following information):**
Until the previous version the functionality worked correctly in my phone:
 - Device: Samsung S6 (SM-G920F)
 - OS: Android 7.0

**Additional context**
I tried to uninstall and reinstall the app but the problem remained.
Also I confirm that in the app v0.8.6-beta.5 (which I have now reinstalled) the functionality is visible and works properly.

**Comment by thanksmister** [comment]
There were some changes in the last update because I had to migrate the code base to a newer version of Android for its new 64 bit requirements for applications.  I will have to retest this and see where its broken or if this is an issue with the library I use for fingerprint unlock.

**Comment by thanksmister** [comment]
Looks like the library I am working no longer works with the newer version of Android.  I will have to update the fingerprint library to get it to work again.

**Comment by giuseppeg88** [comment]
Is there any news on this bug? I am available for any tests.

**Comment by thanksmister** [comment]
This feature has been removed for lack of cross device support.
