### ISSUE TITLE
MQTT Climate Controller

### ISSUE THREAD

**Issue by drronnie85** [thanksmister/android-mqtt-alarm-panel#114]
Hi! I use Home Assistant and have thermostat controller, that control my AC and heater. But using phone or laptop for setup temperature isn't very useful for my family. I like Nest device, but it very expensive. And now can't be integrated with HA. 
I think good idea to create climate controller android application. Like MQTT Alarm Panel. It can be used on old phone.

**Comment by thanksmister** [comment]
Yes, that would be something I would use as well.   It would be nice to either add this as as another module or a separate little app that only uses MQTT.   You also have the option to show your HA dashboard in the app, if you want to display the controls for your climate control.   You could possibly make a tab with just one or a few climate related lovelace cards.  There is a preference in the app for home automation platform pages.

**Comment by drronnie85** [comment]
Thank you for your answer. If you will decide to start development of MQTT Climate Control application I will be happy))
