### ISSUE TITLE
Please support pasting in the password field

### ISSUE THREAD

**Issue by jurgenhaas** [thanksmister/android-mqtt-alarm-panel#115]
It appears that you don't allow pasting in the password field when setting up the MQTT broker. I know that this is perceived a security feature by some, but the reverse is true. Secure passwords are very long and real random values that can't be remembered and typing them is almost impossible. In other words, passwords are stored in password managers and should be pasted into the relevant fields from those vaults.

Could you please offer that too or am I doing something wrong?

**Comment by thanksmister** [comment]
You set your broker username and password in the MQTT settings of the application.   This is already enabled in the application.  So I am not sure exactly what you are requesting?

**Comment by jurgenhaas** [comment]
Well, when trying to input the password in the MQTT settings, pasting from the clipboard wasn't available. That was back in October but there is an updated version from November, where this is now working. Thanks.
