### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by taylorgrayson** [thanksmister/android-mqtt-alarm-panel#116]
I had my alarm set to "armed away", and I walked in the house forgetting to disarm. The alarm immediately went off and I opened up the app to disarm. It seemed to be frozen. After a few attempts to get it to pull up the disarm panel, it crashed. I restarted it and it crashed again. And again. I finally had to go to my computer running the security software and disarm it there.

So the symptoms appear to be that it crashes when trying to disarm the alarm in the triggered state.

**Comment by thanksmister** [comment]
I have not been able to reproduce this, also can you maybe provide information about which system you are using, device, OS, etc.
