### ISSUE TITLE
Beep sound does not sound and does not show countdown to disarm

### ISSUE THREAD

**Issue by cej0t4** [thanksmister/android-mqtt-alarm-panel#117]
**Describe the bug**
Thank you very much for your work!

When I activate the alarm away from home I have an account set back after 60 seconds to disarm when I arrive, the screen does not show the countdown and the sound beep to disarm, but home assistant does send the pending status correctly.

**To Reproduce**
1. Arm Away (60sec to arm) * The alarm is triggered with a door sensor
2. I open the door, and the screen does not show the countdown and the beep sound.

**Expected behavior**
The screen would have to show the countdown and would have to reproduce the beep sound

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 5A
 - OS: havoc os 2.7 (Android 9)
 - Browser: Via browser with android webview
 - Version: 76

**Comment by denkyem** [comment]
I'm having the same issue

**Comment by thanksmister** [comment]
Check the documentation and be sure you have setup your MQTT Alarm Control Panel component properly.  There is no issue with the application, it is most likely that the setup for MQTT Alarm Control Panel does not have enough time between triggering the alarm and the alarm countdown.  The application is only reacting to the MQTT command states.

**Comment by denkyem** [comment]
Actually, this is working for me but only one time after restart the smartphone.
To work again, only after restart it again.

But I will try with the defaults time values and check all the configurations.
Thank you

**Comment by thanksmister** [comment]
@denkyem  That could be an issue with your network connection or MQTT service, it sounds like the connection is broken between the application and the MQTT broker.
