### ISSUE TITLE
[Question] The main display with the "lock" does not go back to disarm (green) after pin code

### ISSUE THREAD

**Issue by bonjour81** [thanksmister/android-mqtt-alarm-panel#118]
Hi there!
I'm new to the app, so maybe I missed something.
So far I have connected the app to mqtt.
I do not use homeassistant and wanted to evaluate the app to use with node-red only.

So, when I launch the app, I have big green lock and mention "systeme desactivé" (system disabled).
I click on it, I am asked to select "yellow" or "red" option (home & away mode).
I pick one.
I can see the matching mqtt publish, for example:
`home/alarm/set ARM_AWAY`

Then, if I click on the lock (I want to go back to alarm disabled):  I am asked for the pin code.
I enter the pin code and I can see the mqtt publish "disarm" message
`home/alarm/set DISARM `.... but the display stay with the yellow or red lock !

Is this a bug or a lack of configuration ?
If I don't use home assistant..is there any command or settings to consider for this basic tasks ?

Best regards,

**Comment by thanksmister** [comment]
The application is not your MQTT broker, only the broker can send the command back to the application that away mode or home mode was successful.   So the application is waiting for the response form the broker.   Think of this application as an interface to your MQTT broker and your alarm status.  I send commands, but it does not actually set your alarm mode and it is waiting for a response that the mode is not set to away or home, it is subscribing to your broker for that response.

**Comment by bonjour81** [comment]
ha ok

I think I found the section in readme file.
I published "disarmed" in "home/alarm" as an answer to the DISARM in home/alarm/set and the button is back to green.

**Comment by flamingm0e** [comment]
I am seeing much the same thing here.

If I arm/disarm from HA Alarm Panel, it doesn't update the state on the MQTT Alarm Panel.

If I arm/disarm from MQTT Alarm Panel, it updates the state of the HA Alarm Panel, and the armed state shows up on MQTT Alarm Panel, but disarming does not change the state on MQTT Alarm Panel.  If I exit out and reload the app, the state is correct.

I feel like I am missing something here.  MQTT shows everything is working as it should.

`homeassistant/alarm` shows correct state when `homeassistant/alarm/set` is published with the correct payload.

**Comment by flamingm0e** [comment]
To follow up with more information:

This appears to only be happening when I change the alarm topic within the app.  If I use the default `home/alarm` and `home/alarm/set` on my HA MQTT Alarm Panel, it works as expected.  It seems like the app isn't listening to the topic you set it to.
