### ISSUE TITLE
Broken compatibility with Android 5.1.1 Lollipop

### ISSUE THREAD

**Issue by nicolaasuni** [thanksmister/android-mqtt-alarm-panel#119]
**Describe the bug**

On Android 5.1.1 the application crashes if the SSL option is set, the port is set to 8883, and the username and passwords are set.

The version v0.8.6-beta.5 is the latest fully working compatible with Android 5.1.1 (lollipop).

Versions starting from v0.8.7-beta.1 requires "javax.net.ssl.SNIHostName" that is only available from Android SDK version 24 that corresponds to Android 7.

I tried to recompile the source code for Android SDK 22 but it seems that the current code has several dependencies on Android SDK greater than 24.

**To Reproduce**
0. Use Android 5.1.1.
1. Go to settings/MQTT
2. Set the SSL mode
3. Set the port to 8883
4. Set username
5. Set password
3. go back to the main page
4. the application crashes.

**Expected behavior**
The application should not crash.

**Screenshots**

This is a log of the crash. This is on a version I compiled but in the released versions the error is the same:
`
E/AndroidRuntime(28531): FATAL EXCEPTION: MQTT Con: 133c2eb1651699610be312310d1079cb0a4125143
E/AndroidRuntime(28531): Process: com.thanksmister.iot.mqtt.alarmpanel, PID: 28531
E/AndroidRuntime(28531): java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/net/ssl/SNIHostName;
E/AndroidRuntime(28531): 	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:139)
E/AndroidRuntime(28531): 	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:722)
E/AndroidRuntime(28531): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(28531): Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.net.ssl.SNIHostName" on path: DexPathList[[zip file "/data/app/com.thanksmister.iot.mqtt.alarmpanel-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime(28531): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(28531): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(28531): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(28531): 	... 3 more
E/AndroidRuntime(28531): 	Suppressed: java.lang.ClassNotFoundException: javax.net.ssl.SNIHostName
E/AndroidRuntime(28531): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(28531): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(28531): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(28531): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(28531): 		... 4 more
E/AndroidRuntime(28531): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
E/AndroidRuntime(28732): FATAL EXCEPTION: MQTT Con: 9b15a1129f142177157dc9dea15cb0be95ecfb
E/AndroidRuntime(28732): Process: com.thanksmister.iot.mqtt.alarmpanel, PID: 28732
E/AndroidRuntime(28732): java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/net/ssl/SNIHostName;
E/AndroidRuntime(28732): 	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:139)
E/AndroidRuntime(28732): 	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:722)
E/AndroidRuntime(28732): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(28732): Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.net.ssl.SNIHostName" on path: DexPathList[[zip file "/data/app/com.thanksmister.iot.mqtt.alarmpanel-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime(28732): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(28732): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(28732): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(28732): 	... 3 more
E/AndroidRuntime(28732): 	Suppressed: java.lang.ClassNotFoundException: javax.net.ssl.SNIHostName
E/AndroidRuntime(28732): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(28732): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(28732): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(28732): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(28732): 		... 4 more
E/AndroidRuntime(28732): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
`

**Smartphone (please complete the following information):**
 - Device: SV98LN Amazon Fire Tablet 5th gen 2015 (ford)
 - OS: Android Nexus
 - Version: 5.1.1

**Additional context**
This app is very useful to create a wall control panel using an old tablet. Unfortunately an old tablet runs only older Android versions, so it is important to maintain the compatibility with at least Android 5.1.1.

**Comment by thanksmister** [comment]
We cannot be completely compatible with older system due to the restrictions Google itself implemented requiring all applications in the Google app store to be 64 bit compliant.   This always means I had to update to AndroidX libraries and also update the Paho MQTT library.  These changes are breaking some devices and there is nothing I can do to support those devices going forward.

**Comment by thanksmister** [comment]
I guess Paho MQTT library would have to make their library compatible with Android 5.1.1, you could report the bug on their Github page. https://github.com/eclipse/paho.mqtt.android
