### ISSUE TITLE
App is not updated by mqtt messages from HA

### ISSUE THREAD

**Issue by jncanches** [thanksmister/android-mqtt-alarm-panel#12]
Hi,

I've installed you Alarm Control Panel app.
It looks very good but I cannot set it up to work.

I've setup HA with a simple configuration (I followed your example in your doc)
- platform: manual_mqtt
  state_topic: homeassistant/alarm
  command_topic: homeassistant/alarm/set
  pending_time: 60
  trigger_time: 1800
  disarm_after_trigger: false
  delay_time: 30
  armed_home:
    pending_time: 0
    delay_time: 0
  armed_away:
    pending_time: 60
    delay_time: 30

I have setup the app (same values for all pending and delay times as HA)

Both HA and the app are succefully connected to my mosquitto broker

When I open the app, I can set an alarm mode and HA reflect the selected state as expected.
BUT after that, I cannot change the state anymore in the app.
Moreover, if I change the state from HA, the good state is not reflected in the app.

Am I missing something ?

Thanks a lot for your help.

JN

**Comment by jncanches** [comment]
Hi,

I found the problem : 
I used /homeassistant/alarm as mqtt topic for my alarm
Changing it to /home/alarm resolve the problem

Is it still an issue ?

**Comment by thanksmister** [comment]
This should have already been addressed. I will have to retest.

**Comment by thanksmister** [comment]
I tested this in v0.7.3 and changing the settings from /home/alarm to /homeassistant/alarm updates both the publish and subscribe for the MQTT service as expected.   I am closing this issue for now.
