### ISSUE TITLE
Add sending alarm value template option when arming and disarming the alarm. 

### ISSUE THREAD

**Issue by jaburges** [thanksmister/android-mqtt-alarm-panel#122]
**Is your feature request related to a problem? Please describe.**
Currently the code is on the end point/your app (NOT HA). This means if you use mobile app or web UI you don't need a code to arm/disarm.

**Describe the solution you'd like**
Given the use case of enabling the Alarm panel in the UI for web access and mobile app access, it would be great to be able to have a code in HA. This would then need you to enter the code in the alarm panel. The user would then enter their alarm code in your app, and it would send the required alarm code via [MQTT as per the docs](https://www.home-assistant.io/integrations/alarm_control_panel.mqtt/) in the message when armed or disarmed. 
```
code: xxxx
```
They could be different, but they also could be the same - user preference I guess.
Thanks

**Comment by thanksmister** [comment]
The HA alarm control panel does not accept the code through MQTT, this would need to be implemented first.  This is why I recommend in the documentation to use the same code as HA, but that code is not passed to HA.

**Comment by jaburges** [comment]
Apologies I’m not sure I follow? The HA alarm control panel does accept a code if enabled:
https://www.home-assistant.io/integrations/alarm_control_panel.mqtt/

**Comment by jaburges** [comment]
Apologies I’m not sure I follow? The HA alarm control panel does accept a code if enabled:
https://www.home-assistant.io/integrations/alarm_control_panel.mqtt/

**Comment by thanksmister** [comment]
It does not receive and process a code value sent over MQTT.  It does form the HA front end, which calls the service directly.

**Comment by jaburges** [comment]
Thank you, let me know if you need me to test/or any feedback etc. appreciate you taking on the feature.

**Comment by thanksmister** [comment]
I could not use the the following commands in the configuration file for the MQTT Manual Alarm Panel:

```
code_arm_required
(boolean)(Optional)

If true the code is required to arm the alarm. If false the code is not validated.

Default value:

true

code_disarm_required
(boolean)(Optional)

If true the code is required to disarm the alarm. If false the code is not validated.

Default value:

true

command_template
(string)(Optional)

The template used for the command payload. Available variables: action and code.

Default value:

action

command_topic
(string)(Required)

The MQTT topic to publish commands to change the alarm state.

device
```

**Comment by thanksmister** [comment]
I am not sure what is going on, there was a breaking change in the latest home assistant so I am trying to configure the new arming, disarming along with sending an command_topic.  I cannot save the configuration:

```
Invalid config for [alarm_control_panel.manual_mqtt]: [code_disarm_required] is an invalid option for [alarm_control_panel.manual_mqtt]. Check: alarm_control_panel.manual_mqtt->code_disarm_required. (See ?, line ?). 
```

https://www.home-assistant.io/blog/2020/05/20/release-110/#read-more

**Comment by thanksmister** [comment]
It appears there is a mismatch between the documentation for the MQTT Manual Alarm Panel and the actual functionality.  There is also a disconnect between the documentation of the Manual Alarm Panel and the MQTT Manual Alarm Panel which it is based upon.  For now, it looks like there is no to implement this feature or any of the new states for the Alarm Panel until these issues are resolved in Home Assistant.

**Comment by thanksmister** [comment]
I have posted a question on the home assistant community https://community.home-assistant.io/t/mqtt-manual-alarm-panel-issues/198398.

**Comment by thanksmister** [comment]
We now integrate with alarmo which supports codes and have a remote code option in the app to send the code to the server.
