### ISSUE TITLE
Application keeps waking up smartphone

### ISSUE THREAD

**Issue by sylvaindd** [thanksmister/android-mqtt-alarm-panel#124]
**Describe the bug**
It seems that the app keeps waking up my tablet every minute or so.
I installed and configured the app on my smartphone and I get  the same issue.
Maybe it's because it seems to receive the disarmed payload on the MQTT every minute (check screenshots). When I check the MQTT, the topic didn't update.

**Screenshots**
![Screenshot (31 mars 2020 15_23_26)](https://user-images.githubusercontent.com/5629405/78031612-12f21400-7364-11ea-8372-6128646c496e.png)
![Screenshot_20200331-152938_Alarm Panel](https://user-images.githubusercontent.com/5629405/78031948-87c54e00-7364-11ea-9112-dc91e5037e72.jpg)
![image](https://user-images.githubusercontent.com/5629405/78032204-f30f2000-7364-11ea-9f81-be04e56c4fb7.png)

**Smartphone (please complete the following information):**
 - Tablet : Lenovo TB-8703X Android 6.0.1
 - Smartphone : Galaxy S10+ Android 10

**Comment by thanksmister** [comment]
Yes, please do not keep resending the MQTT message repeatedly, the application is programed to react to this message.   This is by design and not a bug.  You have something going on with your MQTT broker, which is constantly sending the MQTT disarm message.

**Comment by sylvaindd** [comment]
The message is not constantly being sent.
However, the retain flag is set to 'true'.
I subscribed to the topic and didn't see any message sent (but the application did).

**Comment by thanksmister** [comment]
You said in your original post "Maybe it's because it seems to receive the disarmed payload on the MQTT every minute (check screenshots)."   It cannot receive the disarmed payload unless it is being sent from some place?

**Comment by thanksmister** [comment]
You also have the same issue on two different devices talking to the same broker.  I have to assume this is an issue with your setup since I and others are not experience this issue.   You can subscribe to the message in Home Assistant development under MQTT and see if its being broadcast multiple times.

**Comment by thanksmister** [comment]
> The message is not constantly being sent.
> However, the retain flag is set to 'true'.

How are you setting the retain to true, are you using Home Assistant and the MQTT Manual Alarm Control panel.  I am asking because it does not have an option to set the retain message, and you are setting it somehow manually.

**Comment by sylvaindd** [comment]
Well it's still happening, no message seen by HA.

![image](https://user-images.githubusercontent.com/5629405/78040482-c3b1e080-736f-11ea-92c2-084733ab3285.png)

![image](https://user-images.githubusercontent.com/5629405/78040609-f8259c80-736f-11ea-86ff-1108f8622ef2.png)

The retain flag is not set to 'true' by default ? I don't know what could change this.
Here's my configuration in HA :
alarm_control_panel:
  - platform: manual_mqtt
    state_topic: home/alarm
    command_topic: home/alarm/set
    pending_time: 20
    delay_time: 20
    trigger_time: 120
    disarmed:
      delay_time: 20
      trigger_time: 20
    armed_home:
      pending_time: 20
      delay_time: 20
    triggered :
      pending_time: 20

**Comment by thanksmister** [comment]
I just ran another test on the latest version of the application, I cannot see multiple messages coming in from HA and the application is not having issues with waking up.  Maybe something with your devices is killing the background service?   But I do not think this is app related.  I have to check if HA automatically ads retain, it should not matter if it does, just curious about your setup.

**Comment by thanksmister** [comment]
here is what I have for my configuration but I do not think that is the issue

```
alarm_control_panel:
  - platform: manual_mqtt
    state_topic: home/alarm
    command_topic: home/alarm/set
    pending_time: 60
    trigger_time: 1800
    disarm_after_trigger: false
    delay_time: 30
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      pending_time: 60
      delay_time: 30
```

**Comment by sylvaindd** [comment]
I set a new HA and mosquitto today, so the retain flag is still true.
But I tried again with my smartphone and the problem didn't appear.
However with the tablet, it still happened on both brokers.

Here are the logs from mosquitto :
1586095433: New client connected from 192.168.0.78 as 11216a8f14516015b14fe2f71009d919ab8121de (c0, k60, u'HAAlarm').
1586095438: Client 11216a8f14516015b14fe2f71009d919ab8121de disconnected.
1586095444: New connection from 192.168.0.78 on port 1883.
1586095445: New client connected from 192.168.0.78 as cb17ae5ff93175b4f112bc315a17213df091fe (c0, k60, u'HAAlarm').
1586095534: Client cb17ae5ff93175b4f112bc315a17213df091fe has exceeded timeout, disconnecting.
1586095534: Socket error on client cb17ae5ff93175b4f112bc315a17213df091fe, disconnecting.
1586095535: New connection from 192.168.0.78 on port 1883.
1586095536: Client cb17ae5ff93175b4f112bc315a17213df091fe disconnected.
1586095536: New client connected from 192.168.0.78 as cb17ae5ff93175b4f112bc315a17213df091fe (c0, k60, u'HAAlarm').
1586095625: Client cb17ae5ff93175b4f112bc315a17213df091fe has exceeded timeout, disconnecting.
1586095625: Socket error on client cb17ae5ff93175b4f112bc315a17213df091fe, disconnecting.
1586095626: New connection from 192.168.0.78 on port 1883.
1586095627: Client cb17ae5ff93175b4f112bc315a17213df091fe disconnected.
1586095627: New client connected from 192.168.0.78 as cb17ae5ff93175b4f112bc315a17213df091fe (c0, k60, u'HAAlarm').
1586095716: Client cb17ae5ff93175b4f112bc315a17213df091fe has exceeded timeout, disconnecting.
1586095716: Socket error on client cb17ae5ff93175b4f112bc315a17213df091fe, disconnecting.
1586095717: New connection from 192.168.0.78 on port 1883.
1586095718: Client cb17ae5ff93175b4f112bc315a17213df091fe disconnected.
1586095718: New client connected from 192.168.0.78 as cb17ae5ff93175b4f112bc315a17213df091fe (c0, k60, u'HAAlarm').

It appears that the tablet disconnets every 90s because of a timeout.
Do you know if this can come from the client ? Maybe because of the Android version being old.

**Comment by thanksmister** [comment]
It could be that your tablet cannot store information in the database.  Check the permission for the application or uninstall the application and reinstall, be sure to grant all permissions.   Your device or table should retain its connection, if its continually disconnecting, it could be that your tablet is putting the wifi to sleep.  You should have the application running in the foreground and use either the built in screen saver or Daydream if you have that on the device.  Did you mention which device and which operating system you have on the tablet?

**Comment by sylvaindd** [comment]
It's a Lenovo TB-8703X Android 6.0.1

I reinstalled the application, and it's still happening. I remove the application from battery optimization as well.
I don't think the wifi is going to sleep, I started a continous ping from my PC to the tablet and didn't fail once.
I am using the clock screensaver.

**Comment by thanksmister** [comment]
I suspected it was a Lenovo.  If you search issues, most are with this tablet for some reason.   I am not sure I can help with the issue for a specific device.  I believe the application is functioning normally, but it appears your Lenovo tablet is disconnecting from your MQTT broker, which is causing the loop.  I think here were tips about how to get Lenovo tablets to stay connected if you search the closed issues.

**Comment by sylvaindd** [comment]
I changed to a new tablet (running Android 9) and no problems anymore.

I am closing this issue, thanks for you help.

**Comment by thanksmister** [comment]
Thanks, I suspect Lenovo is always going to be the issue.
