### ISSUE TITLE
MQTT command to change view in the app

### ISSUE THREAD

**Issue by rasweh** [thanksmister/android-mqtt-alarm-panel#125]
Thank you for a great app!

I'm using the Manual Alarm component in Home Assistant and have made an automation that checks doors, windows, motion sensors and more when we try to arm the alarm. If motion is detected, doors are open etc. the automation will block the arming of the alarm and use the TTS function in your app to tell the user that the alarm cannot be armed.

I also use the webview in the app to show a Lovelace dashboard with a list of all the sensors that are checked in the above mentioned automation. So when the system denies arming the alarm we can check the webview in the app to see which of the sensors that block arming the alarm.

But: I'm not sure everybody in the family will remember to switch to the webview when arming the alarm is blocked...

A solution would be to extend the command possibilities in the app so that we could publish a MQTT message to the app to tell it which view the app should show: 'panel' and 'webview' would be handy.

That way I could make my automation also send a MQTT command to the app to tell it to switch to the webview and thereby automatically show the user the list of sensors (or whatever we have decides should be shown in the webview).

**Comment by mreiling** [comment]
Yes, this feature would be huge.  Or for example, switching to the alarm view when the door is opened and the alarm is armed, so one can easily disarm the alarm.

**Comment by mreiling** [comment]
Can you point me to the right section in the code and I can try and do a PR to address this?  Thanks!

**Comment by thanksmister** [comment]
@mreiling you would have to add a new MQTT command, then in the main fragment you can switch between the two views, it's using a pager widget to do the sliding action.   You have access to MQTT commands from the main fragment, there is an observable that listens for database changes.  

When we receive a new MQTT message, we save it to the database and we switch action on the type of MQTT message.   You would use the MQTT command method outlined in the documentation to just add a new command type, then react to this type in the main fragment to switch the pager view.  Hope that makes sense.
