### ISSUE TITLE
Panel not changing in response to payload

### ISSUE THREAD

**Issue by fshelton79** [thanksmister/android-mqtt-alarm-panel#128]
Describe the bug
I can manually issue a payload of DISARM or ARM_AWAY.  I see this updating on the broker, but the panel itself does not update.

To Reproduce
Issue a manual MQTT command with a different payload

Expected behavior
When the topic setting changes in the broker, I expect the panel itself to change and match it

Smartphone (please complete the following information):
Tested on Fire HD 8 Tablet

Additional context
swiping to browser, or closing and reopening the app corrects the state

**Comment by thanksmister** [comment]
The panel is just a reflection of the MQTT broker state, if you send command to disarm or arm you panel, one is returned from the MQTT broker.  Check the logs in the application settings, the top menu icon.   If you do not see the returned call from the MQTT broker, then it is your server.

**Comment by fshelton79** [comment]
I don't see any logs populating....I am guessing that is bad.

**Comment by thanksmister** [comment]
It is not getting the messages, maybe you can restart your mqtt, or check mqtt logs, to see if you have client disconnect issues.

**Comment by fshelton79** [comment]
After I put in the PIN to disarm, I see the topic is updated, but why doesn't the panel itself show it's disarmed?  I apologize if this should be obvious as I am new to MQTT.

**Comment by thanksmister** [comment]
Because the MQTT broker, that is installed in Home Assistant, must send back the MQTT response message.  The alarm does not handle the state of your MQTT broker, it just displays the different states and sends commands.  The MQTT Manual Alarm Panel component in Home Assistant, upon disarming, will send an MQTT message,  The application must subscribe to and recieve this message.

**Comment by fshelton79** [comment]
So I can manually set /home/alarm/set to DISARM or ARM_AWAY on the broker, but this does not reflect on the app unless I exit the app and reopen it.  Is this expected behavior?

**Comment by thanksmister** [comment]
If you set your alarm using the MQTT Alarm Control Panel itself, the widget you add to Home Assistant, it will send a out a topic with a payload to any MQTT application subscribed to it:

When the state of the manual alarm changes, Home Assistant will publish one of the following states to the state_topic:

‘disarmed’
‘armed_home’
‘armed_away’
‘armed_night’
‘pending’
‘triggered’

That means, the payload ‘disarmed’ or ‘armed_away’ is sent out to the application.   If the application sends a MQTT command with payload  DISARM or ARM_AWAY then the MQTT Alarm Control Panel will send back a message on the the subscribed topics with payload  ‘disarmed’ or ‘armed_away’.   That is how it works. 

What I am telling you is, the app isn't broken, there is no bug, either your MQTT broker is not sending out the MQTT response message when it receives DISARM or ARM_AWAY  or the client is getting disconnected by your MQTT server.  Either way, its an issue with your setup, not with the application.  I cannot fix your MQTT setup.

**Comment by fshelton79** [comment]
Thank you.....I appreciate the explanation!

**Comment by thanksmister** [comment]
Please review the documentation for how the MQTT Manual alarm panel works in home assistant and also the documentation on how this application subscribes to and sends MQTT commands to this component: 

https://www.home-assistant.io/integrations/manual_mqtt/
https://github.com/thanksmister/android-mqtt-alarm-panel#example-home-assistant-setup

You have something wrong in either the way you managed your config, your MQTT server, or you changed some setting that does not sync with the server.
