### ISSUE TITLE
Feature request: Fingerprint sensor

### ISSUE THREAD

**Issue by sjvc** [thanksmister/android-mqtt-alarm-panel#13]
Would be great to add support for disarming the alarm with fingerprint sensor :)

**Comment by thanksmister** [comment]
Sure give me a pull request for that feature.

**Comment by sjvc** [comment]
I've just sent a pull request for adding fingerprint support. It works, but you may want to check source code and modify as you like.

**Comment by thanksmister** [comment]
I am going over it now as well as your suggestion for removing the duplicate dependencies, good catch on that one.  I was stumped and research pointed me to using multidex which I didn't want to do.  I will try to resolve that conflict.

**Comment by thanksmister** [comment]
I merged the changes into master, they will be available in the next release, which is v0.7.4
