### ISSUE TITLE
Night mode not working

### ISSUE THREAD

**Issue by ivanfor** [thanksmister/android-mqtt-alarm-panel#131]
**Describe the bug**
Night mode seems to be working only for 1-2 secs. After sending the below_horizon payload, night mode gets activated for a while, but quickly changes to day mode.
Is there anything I can do to debug?

**To Reproduce**
1. Activate night mode in settings
2. Send the following mqtt message: "alarmpanel/command {'sun':'below_horizon'}"

**Expected behavior**
Screen change to night mode and keep in night mode untill above_horizon payload is sent.
Instead, it quickly change to day mode again ....

**Smartphone (please complete the following information):**
 - Device: Unbranded chineese tablet
 - OS: Android 9

**Comment by UVClay** [comment]
I just tested this on my tablet and it's working as expected for me, even with the retain flag explicitly set to false (dunno if that'd actually make a difference in this case, but I tested it both ways just to validate).

**Comment by ivanfor** [comment]
Sorry for not updating. It started to work normally after a couple of restarts. Don't know if it's was android issue or an app issue, but it has worked OK since then. 
It can be closed.
