### ISSUE TITLE
Can it be used in conjunction with BWAlarm?

### ISSUE THREAD

**Issue by fribse** [thanksmister/android-mqtt-alarm-panel#134]
**Is your feature request related to a problem? Please describe.**
I have set up the BW Alarm and have used the WallPanel app to show the BWAlarm interface.
Would it be possible to use this panel instead (more correct I guess?)

**Describe the solution you'd like**
A way to have the BWAlarm armed (night, home, away, panic) with multiple users through the very pretty and dedicated alarmpanel app.

**Describe alternatives you've considered**
I've set up WallPanel to show the URL for the BWAlarm interface, which is nice and works, but it would be great to have a more specialized app for it

**Comment by thanksmister** [comment]
Your feature request is not clear.  Are you asking me to specifically add a feature to work with BW Alarm (I am not familiar with this) or are you asking to have multiple users, are you asking to have other modes like night and panic?  Please clarify your request if possible.   This application works with the Manual MQTT Alarm Panel component in HA (https://www.home-assistant.io/integrations/manual_mqtt).   We do not currently implement night mode and there is no panic mode in the Manual MQTT component. Also there is no support for having codes sent to the Manual MQTT component at this time.  So the app does not offer support for multiple users.   The code feature offered is entirely within the application.

**Comment by fribse** [comment]
Hi @thanksmister 
Even if my question was unclear, you answerede it perfectly :-D
I've set up BWALarm, and just wanted to know if I could use the alarmpanel app for controlling it, and you saíd no, so that's clear, thankyou!
I will just use wallpanel as a 'kiosk browser' and show the bwalarmpanel

**Comment by thanksmister** [comment]
Well, what I said was that alarm panel talks to the HA component Manual MQTT, it has nothing to do with BWALarm.  BWALarm also talks to the HA Alarm, so there is no direct communication between BWALarm and Alarm Panel.  They both should talk to the same HA alarm component I would assume.  BWALarm does not appear to be its own component, it's just a lovelace UI element that is talking to the underlying HA Alarm component.

**Comment by fribse** [comment]
BWAlarm is a custom component, so I guess there is currently no way to support that...
