### ISSUE TITLE
No notification sounds on Amazon Fire (during alarm or during pre-arm delay)

### ISSUE THREAD

**Issue by derekatkins** [thanksmister/android-mqtt-alarm-panel#137]
**Describe the bug**
Even after upgrading to the new features in 0.8.7b1, I am not getting any sounds out of my Amazon Fire HD 8 devices.  I have all audio settings on max; I have chosen valid sounds; I have turned on sound notifications in the "Sounds" preferences.  But I am not hearing anything

**To Reproduce**
1. Go to Settings -> Notifications
2. Click on System Sounds
3. Return to Alarm
4. Arm Away
5. Notice no sounds during the countdown.
6. Wait; let the system arm
7. Trigger the alarm
8. Notice no beeping in the open delay, either.

**Expected behavior**
After the changed we put into 0.8.7, I expected beeping to happen.  I know it happened in my debug station, and I *THOUGHT* I tested the release on the pad prior to installation, but I've noticed that I don't hear anything and (sorry) only now got to reporting it.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Amazon Fire HD 8 (8th Gen)
 - OS: FireOS 6.3.1.5
 - Browser N/A
 - Version Alarm Panel 0.8.7b1

**Additional context**
I know that there were some issues on Amazon Fire devices, but I thought this one was fixed?  Or was there another special setting I had to make?  I didn't find anything in the docs.

**Comment by thanksmister** [comment]
I tested this also, and yeah, it had beeping.   I updated the code a bit but It was working.  I have to retest this, thanks!
