### ISSUE TITLE
sun.sun not working

### ISSUE THREAD

**Issue by wes1993** [thanksmister/android-mqtt-alarm-panel#139]
**Describe the bug**

**To Reproduce**
Send this payload not working:

{
  "payload": "{'sun':{{states.sun.sun.state}}}",
  "topic": "alarmpanel/command"
}
or
{
  "payload": "{'sun':{{states.sun.sun.state}}}",
  "topic": "alarmpanel/command"
}

this template state in the template model page:
{'sun':{{states.sun.sun.state}}}
is
{'sun':above_horizon}

**Expected behavior**
The app change color
**Screenshots**

**Smartphone (please complete the following information):**
App version 0.8.65

**Additional context**

**Comment by thanksmister** [comment]
There is no issue with the application, I am not sure why your particular setup is not working.  From the docs, check the format for the payload:  '{''sun'':''{{states(''sun.sun'')}}''}'

**Comment by wes1993** [comment]
Thanks a lot for your fast reply :-D
If i run this:
{
  "payload": "{'sun':above_horizon}",
  "topic": "alarmpanel/command"
}

Work,
With your won't work... :-(
{
  "payload": '{"sun":"{{states("sun.sun")}}"}',
  "topic": "alarmpanel/command"
}

If i listen via MQTT i have this:
Messaggio 1 ricevuto su alarmpanel/command alle 17:01:
{"sun":"{{states("sun.sun")}}"}

**Comment by wes1993** [comment]
seems won't convert sun.sun to value some other suggestion?

**Comment by thanksmister** [comment]
I can evaluate it the developer tools.  Probably issue with quotes. 

<img width="1109" alt="Screen Shot 2020-10-23 at 12 03 13 PM" src="https://user-images.githubusercontent.com/142340/97020386-e08a4d00-1527-11eb-9b7e-9882fc364ffb.png">

**Comment by wes1993** [comment]
MY:
![image](https://user-images.githubusercontent.com/52070589/97020559-fb71b700-1551-11eb-9e9d-f6c05e49de81.png)
Payload:
![image](https://user-images.githubusercontent.com/52070589/97020668-1e03d000-1552-11eb-90ab-c61bcd078569.png)
Mqtt Message:
![image](https://user-images.githubusercontent.com/52070589/97020694-26f4a180-1552-11eb-90c4-bf8980f13dd5.png)

**Comment by thanksmister** [comment]
With the example from the docs:

<img width="1208" alt="Screen Shot 2020-10-23 at 12 06 24 PM" src="https://user-images.githubusercontent.com/142340/97020718-47a80180-1528-11eb-82ce-e0856148aa3f.png">

**Comment by thanksmister** [comment]
It might just be quotes issue, if you have something working in the developer tools template, you should be able to just copy/paste that into the automation.

**Comment by thanksmister** [comment]
Looks like you have a missing quote between your }}} at the end?

**Comment by thanksmister** [comment]
```
{{states('sun.sun')}}

'{"sun":"{{states("sun.sun")}}"}'

```

**Comment by wes1993** [comment]
New:
![image](https://user-images.githubusercontent.com/52070589/97021105-af734200-1552-11eb-801e-36630a76d34e.png)
Mqtt response:
![image](https://user-images.githubusercontent.com/52070589/97021161-c1ed7b80-1552-11eb-8048-2024119f066b.png)

**Comment by thanksmister** [comment]
Can you verify your template in the developer tools section of HA.  Maybe you just cannot get the sun value or don't have it installed.

**Comment by wes1993** [comment]
I have found something:
If i remove the last quotes:
Dveloper tools
![image](https://user-images.githubusercontent.com/52070589/97022352-4f7d9b00-1554-11eb-9ce7-39737950da89.png)
But won't work payload:
![image](https://user-images.githubusercontent.com/52070589/97022442-68864c00-1554-11eb-8416-5d59dfd7d04c.png)
If i put the quotes lost the variable... :-(
![image](https://user-images.githubusercontent.com/52070589/97022710-bbf89a00-1554-11eb-9002-b43f7230cdb5.png)
developer tools
![image](https://user-images.githubusercontent.com/52070589/97022743-c9ae1f80-1554-11eb-8a1b-aece7acdd8aa.png)

**Comment by wes1993** [comment]
If you go to the mqtt and see what your HA send what can you see?

**Comment by wes1993** [comment]
I have found the correct form:

{
  "payload_template": "{'sun':{{states.sun.sun.state}}}",
  "topic": "alarmpanel/command"
}
