### ISSUE TITLE
Persistent night mode

### ISSUE THREAD

**Issue by scsmartt** [thanksmister/android-mqtt-alarm-panel#141]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add an option to enable night mode all the time. Especially useful for those cases where sun.sun is not functioning as expected and a dark background is preferred over the white background. 

**Describe alternatives you've considered**
No alternative available.

**Comment by thanksmister** [comment]
This was previously answered, just send your own below horizon message in your automation.  It will be forever night.
