### ISSUE TITLE
Chrome for App 0.8.6.5

### ISSUE THREAD

**Issue by wes1993** [thanksmister/android-mqtt-alarm-panel#142]
**Is your feature request related to a problem? Please describe.**
I have an old tablet with android 4.2.2 (can’t update) and if I try to access my HA instance I can’t, probably for HTTPS.
But if I use google chrome I can 👍

**Describe the solution you'd like**
So my request is to use chrome instead of stock browser ;)

**Describe alternatives you've considered**

**Additional context**

**Comment by thanksmister** [comment]
Android native applications cannot use the same s browser as your device.  This has also been answered many times already, either use the legacy version of this app ( as listed on the docs) or use Fully Kiosk.

**Comment by wes1993** [comment]
Sorry for my bad research :-(
Thanks a lot for your reply :) I have installed the legacy app but won’t work so I think that the best things is don’t use the HTTP
Part :)
