### ISSUE TITLE
Allow user to activate flash light of the camera

### ISSUE THREAD

**Issue by jandechent** [thanksmister/android-mqtt-alarm-panel#143]
**Is your feature request related to a problem? Please describe.**
I use the camera motion detection feature, but I want it to work, also when it is dark. 

**Describe the solution you'd like**
I would like to have the flash light of the camera activated. Permanent would do, or just when it becomes dark. Regardless, I would like to be able to control it over MQTT. For me, a mqtt way would be enough, so I would manually switch the light when needed. 

**Describe alternatives you've considered**
I have switched on the light in the room...

**Additional context**
I realize, this might shorten the lifetime of the light, when it is activated so long.

**Comment by thanksmister** [comment]
There was no interest in this feature from community, closing.
