### ISSUE TITLE
Arm Night Option

### ISSUE THREAD

**Issue by drmorley** [thanksmister/android-mqtt-alarm-panel#144]
**Is your feature request related to a problem? Please describe.**
Yes, there is no way to set the alarm to "Arm Night" in the app. Setting the alarm to "Arm Night" via the Home Assistant UI also has no effect on the app (i.e., the app does not recognize that the alarm is armed and, therefore, cannot disarm it).

**Describe the solution you'd like**
Add another button in the pop-up dialogue to allow the alarm to be set to "Arm Night" state.

**Describe alternatives you've considered**
Avoid using the "Arm Night" feature.

**Additional context**

**Comment by thanksmister** [comment]
Please refer to the Home Assistant Manual MQTT component documentation.  There is no support for night mode.  That component is what drives the alarm panel.  You would first need to update the Manual MQTT component first before night mode could be supported.  

https://www.home-assistant.io/integrations/manual_mqtt/

**Comment by drmorley** [comment]
According to Manual MQTT component documentation referenced above, it sounds like night mode is now supported. Here's a snippet from the documentation page:

"The integration will accept the following commands from your Alarm Panel via the command_topic:

    DISARM
    ARM_HOME
    ARM_AWAY
    ARM_NIGHT"

BTW, great app! Thanks.

**Comment by thanksmister** [comment]
Well, try the new beta app, it supports night mode.  https://github.com/thanksmister/android-mqtt-alarm-panel/releases/tag/v1.0.1.0

I have not updated the documentation for this version and it must also be side loaded, it's not in google play store.

**Comment by drmorley** [comment]
OK, great. I guess I should've checked there first. Thanks again!

**Comment by thanksmister** [comment]
Nah, that is a stealth project and I have not listed any of the changes publicly.   But I was updating this for an upcoming component update by another contributor and never released it.  Please let me know if you have any issues, you can also join our discord channel. https://discord.gg/tP3kuCrSKa

**Comment by drmorley** [comment]
Thanks, I've installed the beta version and will let you know if I find any issues.
