### ISSUE TITLE
Feature Request: Webpage Shortcut / Widgets

### ISSUE THREAD

**Issue by IyRuK** [thanksmister/android-mqtt-alarm-panel#15]
I would love to be able to have a button to show device which can be controlled, either as a separate tab or button at the bottom. it could either link to a webpage (Home Assistant/OpenHab/Etc) or allow us to add groups and entities to a custom page. kind of like HADashboard. 

If you have an alternative method for this that would be cool!. I very much like your clean look btw! Great Job!

**Comment by thanksmister** [comment]
There is already a button that links to HASS/OpenHAB or any website.  Just go into the application settings and swipe until you get to the Home Automation screen.  Activate this feature and enter the platform address.  Then from the main screen you will see a new button to go to the automation or you can swipe right/left to show the view.
