### ISSUE TITLE
Camera settings not working

### ISSUE THREAD

**Issue by mreiling** [thanksmister/android-mqtt-alarm-panel#150]
**Describe the bug**
When trying to set up camera settings, the app just takes you back to the main alarm panel screen.

**To Reproduce**
1. Go to settings
2. Click Camera
3. App just flashes to a white screen then takes you back to main alarm panel.

**Expected behavior**
Should open up camera settings.  This worked a few times, but never allowed motion settings to be changed.  Now any camera settings cannot be changed..

**Screenshots**
Attached video

https://user-images.githubusercontent.com/45905227/104816843-88837f80-57d2-11eb-911c-696ccd82a637.MOV

**Smartphone (please complete the following information):**
- Device: Fire HD 10
- OS: FireOS 7.3.1.7
- Alarm-Panel Version: v1.0.1-beta.5

**Additional context**

**Comment by thanksmister** [comment]
Hey thanks for reporting the issue, I see an error in Firebase, these seems like your device.

<img width="1192" alt="Screen Shot 2021-01-17 at 5 56 07 PM" src="https://user-images.githubusercontent.com/142340/104855768-6f232600-58ed-11eb-9c09-4185b33f84d1.png">

I have to take a look at what values are allowed, but basically it has a non-number value for the camera motion, is the app possibly crashing when selecting Camera Motion?   Your MOV file didn't play for me.   I am looking at this crash now and will have it in the next update.  I could not however reproduce a crash when opening just the camera settings, only when I selected motion detection button.

**Comment by thanksmister** [comment]
I am uploading a new version v1.0.1.6 to the release section and to firebase for testing.

**Comment by mreiling** [comment]
It originally only crashed when choosing motion, but after a few attempts, maybe like 10, it is now crashing when selecting camera as well.  I updated to b6 but it seems to be happening still.  I rebooted the tablet as well.  Thanks!

**Comment by thanksmister** [comment]
I will look for other crash reports, you man need to uninstall and install again, possibly you entered a bad value and it can’t convert it properly.

**Comment by thanksmister** [comment]
Looks like bad value for camera rotate. 

<img width="1227" alt="Screen Shot 2021-01-18 at 9 28 03 AM" src="https://user-images.githubusercontent.com/142340/104915564-96bad280-596f-11eb-9adf-d6982554db5d.png">

**Comment by thanksmister** [comment]
I have updated a new release https://github.com/thanksmister/android-mqtt-alarm-panel/releases/tag/v1.0.1.7

**Comment by mreiling** [comment]
So that seemed to fix my issues.  Thank you so much.  Unfortunately, I am now plagued with MQTT problems.  It seems to be connected to the broker, but does not act on any changes.  Using a MQTT client and sending messages has no effect either.  At one point it started working randomly but since stopped again.  No commands send seem to work either.  Possible issue with the new MQTT library?  any way to debug on my end?

**Comment by thanksmister** [comment]
It's better if you join the channel and look at the notes others who have this working have posted.  That way we do not have to recreate all the same information here.    The short answer is I don't know your setup, but that is what controls MQTT behavior.  Nothing has changed previously from the way we use the alarm panel with the MQTT manual component.  Here is the Discord channel https://discord.com/invite/euh9J2d, join Alarm Panel group
