### ISSUE TITLE
Visual feedback when entering the code after the alarm is triggered

### ISSUE THREAD

**Issue by giuseppeg88** [thanksmister/android-mqtt-alarm-panel#153]
**Is your feature request related to a problem? Please describe.**
Unlike when entering the disarm code, there is no visual feedback when entering the code after the alarm is triggered, making it difficult to do so.

**Describe the solution you'd like**
It would be wonderful to have feedback on the number of digits already entered (such as, for example, through the dots used during traditional disarming)

**Comment by thanksmister** [comment]
This works as designed now.
