### ISSUE TITLE
Display not updating to correct status + MQTT publishing early

### ISSUE THREAD

**Issue by seanmccabe** [thanksmister/android-mqtt-alarm-panel#160]
**Describe the bug**
Onscreen display does not update when the panel is disarmed via the app or via MQTT.
Also MQTT appears to update before the timer has completed the countdown.

**To Reproduce**
See video.

**Expected behavior**
Expect the display to update to the correct status. I.e. disarmed, panel shows disarmed.
MQTT topic only be set once countdown is completed.

**Screenshots**
[Video](https://1drv.ms/v/s!Ah2pGJksf4r8irk5jXeB_yfmN6zuIQ?e=wOTHaT)
![20210405_095531](https://user-images.githubusercontent.com/12243212/113522658-87563780-95f6-11eb-9597-21d441a18f4c.jpg)
![20210405_095503](https://user-images.githubusercontent.com/12243212/113522653-83c2b080-95f6-11eb-8799-706822239928.jpg)

**Smartphone (please complete the following information):**
 - Device: Ollee M16071A
 - OS: Android 5.1.1

**Comment by thanksmister** [comment]
Check the internal logs, we log each incoming message.   You are also on an older version of the application, though not everyone has access to the new version through Google Play.   Please visit the release section to install the latest if possible.

**Comment by thanksmister** [comment]
I don't think this ticket is valid as there is now a new version.   If the issue persists, please file a new bug.
