### ISSUE TITLE
Error to load HA

### ISSUE THREAD

**Issue by ivanaragom** [thanksmister/android-mqtt-alarm-panel#161]
When I try to log into Home Assistant, the page goes blank and does not login.
I test from chrome and it works perfectly and from the official HA app as well.

When I refresh the screen it asks me again for my username and password

 - Device: dahua vth5321gw (px30 evb)
 - OS: Android 8.1
 - WebView 61.0.3163.98

**Comment by thanksmister** [comment]
This isn’t an issue with the application, your device or software version doesn’t support the css/html of the web page you are trying to render.  Android apps use WebView not Chrome to render pages.  Either load a less complex website or use Tileboard instead of HA for your front end.
