### ISSUE TITLE
Bottom Bar

### ISSUE THREAD

**Issue by netracernz** [thanksmister/android-mqtt-alarm-panel#165]
I cannot find the option after recent update to remove bottom bar. The option in Browser menu has been unticked yet I cannot seem to remove it from Alarm or browser screen. Has this feature been removed in recent update.

**Comment by thanksmister** [comment]
We no longer have a bottom bar on the browser views. The alarm view always has a bottom bar, it was never removable.

**Comment by netracernz** [comment]
Here is a picture of the bottom bar that I cannot remove

![20210530_122717](https://user-images.githubusercontent.com/38962800/120088209-8945fe00-c142-11eb-9d79-25823c0525cb.jpg)

**Comment by thanksmister** [comment]
The setting is still under the dashboards tab and will be functional in the next release.
