### ISSUE TITLE
doesnt receive anymore weather info and sensor status from MQTT

### ISSUE THREAD

**Issue by morenonew2** [thanksmister/android-mqtt-alarm-panel#166]
Hello
from last beta the app doesnt receive anymore the info relative to weather and sensor status.
I create the relative automation in HA that had functioning until few release ago.
I enable the relative switch on app.
But now, even if the MQTT broker publish regularly, i cannot see nothing

Thanks

**Comment by thanksmister** [comment]
I am not able to reproduce that issue.   The app is receiving MQTT weather data and sensor updates.  I assume you are talking about registering sensors and not sending device sensor data?

**Comment by morenonew2** [comment]
Yes sensors like windows sensors. The strange is that mqtt alarm function like a charm. Only weather, sun and sensor doesnt function

**Comment by thanksmister** [comment]
Have a look at the documentation to verify you are formatting the MQTT payloads correctly for weather and sensors.   Also check your settings to verify all looks good with sensors.   You can do some debugging by subscribing to the same topic using the MQTT configuration under HA integrations.  This will output what is being sent from your own server.

**Comment by morenonew2** [comment]
Thanks. I verify with ha and mqtt explorer and it match with topic anche payload. Is really strange. I also tried with reinstall  all but nothing to do. If you are sure that nothing change in the Last beta, then i'll start to controll yet.

**Comment by thanksmister** [comment]
You haven't said which version you have?  This can be found in settings, about button.   I am using the alarm with weather and sensors, so I cannot reproduce the issue.  I am using v1.1.1-beta.6.

**Comment by thanksmister** [comment]
Maybe some database issue, do you have data backup on for your device?

**Comment by morenonew2** [comment]
Thanks. Now is all ok afferma fresh reinstall. But there is maybe a bug. When i put my tablet in Landscape behaviour and i have alarm sensor without  check " required for setting alarm" I am not able to do anything: no arming no disarming. In portrait mode al is ok.

**Comment by thanksmister** [comment]
Ok, will check that out, but sounds like maybe you had a database error on upgrade.
