### ISSUE TITLE
Provide API to exit / restart the app

### ISSUE THREAD

**Issue by mjsambol** [thanksmister/android-mqtt-alarm-panel#167]
I've been using the MQTT Alarm Panel app together with Fully Kiosk for over a year, and for the most part it's great and I really appreciate it. However, for a long time I've been frustrated with the Sun above/below horizon functionality which is supposed to set the background color. I've had it work intermittently, but more often than not it does not work. 

I have confirmed that temperature and weather updates are received and processed immediately. Sun updates are generally ignored until the app is restarted.

I've tried to work around this lots of different ways. The only way I can consistently get the app to show the "correct" background color is to kill and relaunch it. When it next checks the value from MQTT, it shows the appropriate background.

I assume that figuring out what's wrong with the current functionality is more complex than providing an API which would simply exit the app.

I can restart fully kiosk remotely, but that doesn't restart the alarm panel. I can *launch* the alarm panel remotely using fully kiosk, but can't kill it without rooting the tablet or doing convoluted automations with Tasker.

Thanks.

**Comment by thanksmister** [comment]
No, we are not gong to add this feature, once you exit the app, there is no way to open the app again using the API.  If you want to do something like that, you need to use another app like tasker.  Also, if you want to file an issue, you must provide more information such as your app version, the version of Android you are using.   There could be multiple possibilities for your issue, including your own automations.   This closing and opening the app is not a solution.

**Comment by mjsambol** [comment]
OK, fair enough (except for the comment about my automations). I checked the version and saw that I'm not on the latest, so upgraded and will see if perhaps the problem is resolved.

**Comment by thanksmister** [comment]
If you want attention to multiple issues, you need to make multiple tickets.  I cannot parse each issue in your ticket. Also when filing tickets, follow the format and provide appropriate information.
