### ISSUE TITLE
Vibration feedback when entering the code after the alarm is triggered 

### ISSUE THREAD

**Issue by giuseppeg88** [thanksmister/android-mqtt-alarm-panel#169]
**Your feature request. Please describe.**
Unlike when entering the disarm code, there is no visual feedback when entering the code after the alarm is triggered, making it difficult to do so.

**Are you able to contribute?**
It would be wonderful to have a vibration feedback when entering the password digits.

**Comment by thanksmister** [comment]
Haptic feedback is more difficult as we are not using the built-in keyboard and it does not always work on all devices.   We may consider showing the same behavior as when entering the code on the disarm dialog as a solution.
