### ISSUE TITLE
Feature Request: Portrait Mode?

### ISSUE THREAD

**Issue by IyRuK** [thanksmister/android-mqtt-alarm-panel#17]
I am wanting to use a Wink Relay with your app, but it is only in portrait. was hoping you could allow it to be displayed in Portrait and not just landscape

**Comment by thanksmister** [comment]
I wish it were as simple as just allowing portrait orientation.  However, the application was designed for tablets, and then eventually smaller devices that were to be dedicated alarm panels mounted on the wall or stationary.  Many of the application features are built for this purpose.  What you are really asking for is another application entirely.  Many of the features and the design would have to be changed to accomodate a portrait application.   This app won't support portrait, but one day there may be a scaled down version of the application which does.
