### ISSUE TITLE
Popup text for 'failed to arm' should not be a systemrequester with small letters

### ISSUE THREAD

**Issue by fribse** [thanksmister/android-mqtt-alarm-panel#172]
**Your feature request. Please describe.**
Using a small 5" or 7" tablet for an alarmpanel implementation seems obvious, they don't work that well any longer, and this way it can at least be recycled for some limited purpose. I'm using the Alarmo integration (THANKYOU VERY MUCH FOR DOING THAT!!!!) and if it fails to arm, it shows a very small lettered systempopup. As everything else is nicely formatted with large information screens, it sort of looks odd, and will make it hard for semi visually impaired people.

**Note**
We get many feature requests, each feature requires community support and also development time. Features that have no community support are not considered.   If you are not contributing to the feature, then the feature is taken under consideration after all other feature requests.

**Comment by thanksmister** [comment]
The popup is called an Android snackbar and it is a system component, part of Android.   What I may suggest is maybe increasing your system font size, the component should respond appropriate.   You may also listen to the Alarmo event topic and upon receiving an alarm, send the alarm panel an alert message or TTS.   This works better than me having to create a new component for the snackbar or attempt to handle font sizes for different devices.   I am running the Alarm on a Fire OS7 device, it's not just older devices with smaller screens.

**Comment by fribse** [comment]
Snackbar, ha ha, great name they give them. I guess that would work, but currently I have problems in just exiting the alarmpanel app to get to the android settings :-)

**Comment by thanksmister** [comment]
There is a setting to release the app as the home app, you need to select this, then you can go back to your Android home screen.  This is how Android works when setting an app asa home screen.   Just look for the setting that says remove home screen in the app settings, this will free you.

**Comment by fribse** [comment]
I must be completely blind, I don't see that, we are talking about the settings for the MQTT Alarm Panel App right?
I see
Security Code
Require Disarming Code
Require Arming Code
Panic Button
Theme
Advanced Settings
MQTT Settings
Display
Notification Settings
Camera
Weather
Device Sensors
Browser
About
??

**Comment by fribse** [comment]
Ahh, I found out that  I could access the topbar, and by pulling that down, I could get to the android settings.

**Comment by thanksmister** [comment]
OK, next release I am adding the missing setting, I added it to my other application Wallpanel but not this one, oops!!
