### ISSUE TITLE
Localization of messages

### ISSUE THREAD

**Issue by fribse** [thanksmister/android-mqtt-alarm-panel#173]
**Your feature request. Please describe.**
Not sure if it's somehow already possible, but it would be nice to have the messages shown in your own language.
If need be, give me the strings, and I'll translate them to danish :-)

**Comment by thanksmister** [comment]
The new messages have not yet been translated, that is true.  We have many other languages, but not yet Danish.   The language files are actually xml files and located in this folder structure: 
https://github.com/thanksmister/android-mqtt-alarm-panel/tree/master/app/src/main/res

What you should do is create a pull request, adding a new folder values-da and inside a strings.xml file with your own language translations.  Here is an example for Dutch: https://github.com/thanksmister/android-mqtt-alarm-panel/tree/master/app/src/main/res/values-nl.

**Comment by fribse** [comment]
Hi Thanksmister, I'm absolutely not a git user, but I would love to try. I'll try and google for help on how to do that.

**Comment by thanksmister** [comment]
Alternatively, you can just copy one of the string.xml files, translate it in Visual Code, then pass me the file.

**Comment by fribse** [comment]
I got the repo cloned now, and I've gotten to line 55, so things are progressing :-)

**Comment by thanksmister** [comment]
I think we will close this issue.
