### ISSUE TITLE
[FEATURE] Ability to rename alarm modes

### ISSUE THREAD

**Issue by s31teg** [thanksmister/android-mqtt-alarm-panel#174]
In my house, I have a downstairs alarm & a whole house alarm.

My kids & wife sometimes press the wrong button. So would be nice if the home & away could be renamed or just be able to add additional alarms that can be configured by name, colour, icon possibly?

**Note**
Thanks in advance for any feedback.

**Comment by thanksmister** [comment]
This is not a feature I agree with.  The alarm modes match those supported by HA and alarmó integration.
