### ISSUE TITLE
[BUG] Security code starting with a 0 not working 

### ISSUE THREAD

**Issue by sylvaindd** [thanksmister/android-mqtt-alarm-panel#175]
**Describe the bug**
After updating the app I had to change the security code. I entered a 4 digits code starting with a 0.
Right after that I couldn't access parameters. 

Reinstalled the app to try again, and same problem every times. 

**To Reproduce**
Enter a code starting with a 0 and test it to access parameters. 

**Smartphone (please complete the following information):**
 - Device: Meberry
 - OS: Android 9
 - Applicaiton version : 1.1.1 build 9

**Comment by petervk2** [comment]
Confirmed same behavior for me (with code 0000 anyway), running a Fire7 tablet & Android 7.1.2

**Comment by thanksmister** [comment]
We have an update for this being released to Google Play and Github today.

**Comment by thanksmister** [comment]
https://github.com/thanksmister/android-mqtt-alarm-panel/releases/tag/v1.1.2.0
