### ISSUE TITLE
Disarm while is pending

### ISSUE THREAD

**Issue by morenonew2** [thanksmister/android-mqtt-alarm-panel#179]
**Describe the bug**
When I try to disarm after a few second (with an ext app like HA) it remains stuck in pending mode for a 20 sec. So I cannot retry to arm .

**To Reproduce**
Arm with ext app (HA). After 1 sec I decide to disarm with an ext app (HA) but the system remain stuck in pending mode for a 20 sec. 

**Smartphone (please complete the following information):**
 - Device: lenovo tablet
 - OS:android
 - Applicaiton version [last beta 16.07.2021]

Thank a lot for your big big work

**Comment by ggoodell2** [comment]
are you using the alarmo tile to arm and disarm in HA?

**Comment by morenonew2** [comment]
Thanks. I solve using ALARMO.
