### ISSUE TITLE
Failed to Arm

### ISSUE THREAD

**Issue by morenonew2** [thanksmister/android-mqtt-alarm-panel#181]
A little question.

ALARMO return an event like FAILED_TO_ARM (upcase) but the alarm panel display only a generic message (if I remember.... "unable to arm due to error config" ...... I think). Alarm panel support the event but in lower case (failed_to_arm) Is this the cause of a malfunction ? 
This is the payload return from ALARMO _{"event": "failed_to_arm", "sensors": [{"entity_id": "binary_sensor.openclose_24", "name": "Serranda Bagno"}, {"entity_id": "binary_sensor.openclose_23", "name": "Serranda Matrimoniale"}, {"entity_id": "binary_sensor.openclose_21", "name": "Serranda Cucina"}, {"entity_id": "binary_sensor.openclose_17", "name": "Serranda Sala"}, {"entity_id": "binary_sensor.openclose_22", "name": "Serranda Studio"}]}_
and this is the message from Alarm Panel "_Unable to arm system. Please check settings_" 

Thanks

**Comment by thanksmister** [comment]
I can check, but I believe we convert everything to the same case (lowercase) before we process this.   Thanks for the information.

**Comment by thanksmister** [comment]
We do lowercase all incoming events to compare them against expected application events.   FAILED_TO_ARM or failed_to_arm will be treated the same.   The error message we display when FAILED_TO_ARM is received is as follows:

> Unable to arm system, please check if a sensor is open or the alarm settings

The reason we display a different message than Alarmo is because the app support multiple languages (6 different ones).  So I capture all incoming Alarmo messages and display language specific ones.

**Comment by morenonew2** [comment]
Thanks for the quick response. So there are no way to display on alarm panel the open sensor, like ALARMO send with event payload. 
Thanks

**Comment by thanksmister** [comment]
You can create your own alert message using the Alarmo MQTT event by setting up an automation.  Also the application has sensors built-in, so you can add sensors to the main screen of the application, they have the same features as Alarmo, showing open and close, preventing alarm from arming if sensor is "open" state.

**Comment by morenonew2** [comment]
thanks.
so I can send with an automation a payload like this? and display all the open sensors?
**_{"event": "failed_to_arm", "sensors": [{"entity_id": "binary_sensor.openclose_24", "name": "Serranda Bagno"}, {"entity_id": "binary_sensor.openclose_23", "name": "Serranda Matrimoniale"}, {"entity_id": "binary_sensor.openclose_21", "name": "Serranda Cucina"}, {"entity_id": "binary_sensor.openclose_17", "name": "Serranda Sala"}, {"entity_id": "binary_sensor.openclose_22", "name": "Serranda Studio"}]}_**

**Comment by thanksmister** [comment]
No you would listen for the Alarmó event as the trigger, parse the json and resend a new MQTT alert command (from the documentation under commands) with the message you want to display.

**Comment by morenonew2** [comment]
ok thanks

**Comment by thanksmister** [comment]
https://github.com/thanksmister/android-mqtt-alarm-panel#mqtt-alarm-commands-with-mosquitto
