### ISSUE TITLE
System resets on Home Assistant restart

### ISSUE THREAD

**Issue by joshmd** [thanksmister/android-mqtt-alarm-panel#20]

**Comment by thanksmister** [comment]
Home Assistant issue with persistent MQTT data.  This isn't an issue with thhe application.  Mine sets to away mode on HASS restart.  There is some persistent library fix I've seen. Check the HASS forums.

**Comment by thanksmister** [comment]
Try this library for HASS:  https://github.com/gazoscalvertos/HASS-Persistence.

**Comment by joshmd** [comment]
Thank you I'll check that out!
