### ISSUE TITLE
Add Weather Underground Option

### ISSUE THREAD

**Issue by jccshmny** [thanksmister/android-mqtt-alarm-panel#23]
Add Weather Underground integration for weather.

**Comment by dlashua** [comment]
What might be easier/better/handle more use cases would be to define a payload for weather information and allow users to publish their own weather data to the defined topic. Some sample Home Assistant configs could be offered to make this easier for users using the various Home Assistant weather components.

**Comment by thanksmister** [comment]
Yes I was thinking this but then we would not have the 7-day forecast option.   I wouldn't want to do both DarkSky API mixed with MQTT weather.  It should be one or the other and I am not sure 7-day forecast is a viable option from HASS.  It's a good idea though.

**Comment by alertedsnake** [comment]
FYI Weather Underground is deprecating their free API: https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api

**Comment by thanksmister** [comment]
We use DarkSky not weather underground.
