### ISSUE TITLE
Keep screen on when using screen saver

### ISSUE THREAD

**Issue by thanksmister** [thanksmister/android-mqtt-alarm-panel#25]
The screen should remain on when using the screen saver.  Currently a third party application is required to keep the screen on.   Add FLAG_KEEP_SCREEN_ON flag and move screensaver from a dialog to an activity (required for flag to work).

**Comment by thanksmister** [comment]
Added in v0.8.0

**Comment by mvoosten** [comment]
Have to press screen 3 times to get out of screensaver mode..

**Comment by thanksmister** [comment]
@mvoosten you need to fill out an issue in the issue tracker if you think you've discovered a bug.
