### ISSUE TITLE
Update the AndroidThings version

### ISSUE THREAD

**Issue by rafuz** [thanksmister/android-mqtt-alarm-panel#26]
I have seen recent development of the Android version of this app, 
Will andnroidthings version be updated shortly? Will it be upgraded to AndroidThings 1.0?

**Comment by thanksmister** [comment]
All I can say is the project will be updated in the near future when I have time to work on it.  I do plan on upgrading to AndroidThings 1.0 but there are no significant features or bug fixes with 1.0 that require an upgrade.  I am happy to accept pull-requests if there is a feature in the mobile version that you would like to see in the Pi version sooner.
