### ISSUE TITLE
Wake screen on face detection/motion

### ISSUE THREAD

**Issue by aptonline** [thanksmister/android-mqtt-alarm-panel#29]
I’ve just discovered the Android version of the MQTT alarm panel and can’t wait to implement it. I initially started using the wallpanel app after finding it on the home assistant forums and likes the idea of face detection to unlock the screen when it’s sleeping.  Wallpanel development seems to have stagnated and the face unlock feature doesn’t seem to be working for me.

My question is, as you are already using the camera would the ability to add face detection to unlock the screen be something you’d consider adding to the roadmap? If not face detection adding motion detection via the camera? Or even both and give the option (like wallpanel).

Thanks

**Comment by thanksmister** [comment]
Both of those are difficult and time consuming to implement. Especially since we need to support multiple Android devices.  I already attempted motion detection but backed off due to the technical difficulty involved spanning multiple devices.

**Comment by aptonline** [comment]
I understand Android has a built in face detection api, not sure how good that is however. Maybe only available on certain versions of the OS.

Btw the developer of WallPanel is looking for someone to take over the development, maybe the code he’s already made can be used?

https://community.home-assistant.io/t/looking-for-someone-to-pick-up-wallpanel-project/56314

**Comment by thanksmister** [comment]
Yeah, looking at that code now and he implemented another library for motion detection.   I will investigate and see if its something that can be easily integrated into my application.   I prefer motion detection over face detection just to wake the device as you approach the panel.

**Comment by aptonline** [comment]
Wallpanels implementation is 2 fold and works well.

You can have motion wake the screen as you say or just for motion detection and expose this to home assistant via MQTT where it will appear as a sensor. Great for alarm systems. The screen stays off in this implementation.

The face detection option works if you are obvious looking directly looking at the panel and this way you don’t get false wakes where someone is just walking past the screen, as it would in my case.

There’s a toggle in the UI for both these options.

**Comment by thanksmister** [comment]
You can join the beta program if you wish to test the next version before it's released to production here: https://play.google.com/apps/testing/com.thanksmister.iot.mqtt.alarmpanel.  It contains this feature similar to WallPanel.

**Comment by thanksmister** [comment]
This should be available in the latest version v0.8.2 Build 7
