### ISSUE TITLE
Get state of tablet

### ISSUE THREAD

**Issue by aptonline** [thanksmister/android-mqtt-alarm-panel#31]
I’m not sure if this is something that’s currently supported or on the roadmap but the ability to expose sensors on the host tablet to home assistant.

For example:

Battery state
Charging state
Display on/on
Motion detected (when supported)
Face detected (when supported)
Camera snapshot

**Comment by thanksmister** [comment]
That's a lot features.  You can request any feature you like but it comes down to time on my part.  I will mark this as a feature request and see what happens.

**Comment by aptonline** [comment]
I’m just trying to think of all the features that WallPanel has/had seeing as though development has stopped. Basically it had its own REST/MQTT api.

**Comment by thanksmister** [comment]
Yes I see what had, but its not my vision of what I want for my application.   It has some features that I already have such as camera snapshot and others I I might incorporate like motion detection.  However, the vision I have for my application is different.

**Comment by aptonline** [comment]
Fair enough. I know these features would make a great app even better, I’ll watch it’s development with interest and hope some of what’s I’ve suggested makes an appearance.

**Comment by thanksmister** [comment]
You can join the beta program if you wish to test the next version before it's released to production here: https://play.google.com/apps/testing/com.thanksmister.iot.mqtt.alarmpanel.  It contains this feature similar to WallPanel.

**Comment by thanksmister** [comment]
This should be available in the latest version v0.8.2 Build 7
