### ISSUE TITLE
TTS does not respect my current volume

### ISSUE THREAD

**Issue by colinodell** [thanksmister/android-mqtt-alarm-panel#33]
**Expected behavior:** TTS audio plays at the volume level I've set my device to.

**Actual behavior:** Regardless of what I set my tablet's volume to, TTS always changes the volume to ~50%.  If I manually increase the volume back up to 100% it still goes back down to 50% as soon as TTS plays.

Device: Kindle Fire 5th Generation
App version: v0.8.0-beta.6

**Comment by thanksmister** [comment]
Yeah, I think I know what's causing this.  I am setting the media volume when initializing TTS.

**Comment by thanksmister** [comment]
Fixed and tested in v0.8.1. TTS now respects device volume settings.

**Comment by colinodell** [comment]
Awesome, thank you! :bear:
