### ISSUE TITLE
Different codes

### ISSUE THREAD

**Issue by freekeys** [thanksmister/android-mqtt-alarm-panel#34]
Hello - thanks so much for an awesome contribution :)

Does this support multiple codes? I’m thinking then I can have codes that expire to give to cleaners/dog sitter etc ?

Or is there anyway the code typed could be sent to HA? Then you could even monitor incorrect entries too

**Comment by thanksmister** [comment]
No there is no way to send the code to HASS without first updating the HASS manual alarm component to accept codes over mqtt.  The application has only one code possible at this time.

**Comment by benmprojects** [comment]
Have you looked at sending the code to this addon as it already supports multiple pin codes?
https://github.com/akasma74/Hass-Custom-Alarm
