### ISSUE TITLE
clock 24hr format

### ISSUE THREAD

**Issue by fwidfeldt** [thanksmister/android-mqtt-alarm-panel#40]
The clock always display in 12hr format. Would it be possible to use android system setting? Or a configuration in the app?

**Comment by fwidfeldt** [comment]
That's strange. 
Yes, my device is set to 24-hour format, which is used for example in the notification bar. 
But in Alarm Panel, both on the main screen and in the screen saver, 12-hour  format is used.

**Comment by thanksmister** [comment]
I can’t reproduce the behavior. Whatever format I set my system to, the application immediately follows.  Which device and version of Android are you running?

**Comment by thanksmister** [comment]
You shouldn’t need to reboot the application to have device changes reflected within the application such as time format, this should be automatic, at least it is when I update the time format in the settings.  The application time format automatically updates.
