### ISSUE TITLE
Issue with MJPEG transmision

### ISSUE THREAD

**Issue by fcastroruiz** [thanksmister/android-mqtt-alarm-panel#41]
Sorry for my english,

I have a problem with MJPEG transmision I try it in huawei p10 lite and in old tablet , in two cases, i test camera and face motion and work fine , when i use VLC in an iphone with http://192.168.0.x:2071/camera/stream i receive a black screen and nothing more. in Home assistant i receive "not available" 

someone can help me?

**Comment by thanksmister** [comment]
There are a couple things you can try.  

1) Be sure you have MJPEG on in the settings
2) Make sure you don't exceed the number of open feeds (default is 1)
3) In the camera settings lower the frame rate (FPS) and see if that helps

**Comment by thanksmister** [comment]
Seems to be a bug in Alarm Panel that motion detection has to be on in order to receive MJPEG streaming.  Please activate the motion detection option in the settings and see if MJPEG starts working. I will issue a fix soon for the issue.

**Comment by fcastroruiz** [comment]
Thnks i try it and answer later

**Comment by fcastroruiz** [comment]
Point 1. Is on 
Point 2. Value 15
Point 3. FPS 1 id mínimum value??
I active motion detection and same result, black screen, if i put other values or error in http direction VLC not open stream. I use other app “Ip stream in 8080 port and work fine, i try other things, 😔😔😔

**Comment by fcastroruiz** [comment]
I know, that's why I put value 15 (Point 2) . I still don't fix it

**Comment by thanksmister** [comment]
There is anew update with fixes for MJPEG available.  Please update and try again.

**Comment by fcastroruiz** [comment]
Now work fine!!!!!!! Thnks a Lot!!! Now one problem in huawei lite work perfectly but in old tablet image is flipped, is posible to change flip??

**Comment by thanksmister** [comment]
> Now one problem in huawei lite work perfectly but in old tablet image is flipped, is posible to change flip??

That is a feature that would need to be added.  Do you mean flipped or rotated?
