### ISSUE TITLE
UI issues with keypad elements

### ISSUE THREAD

**Issue by aptonline** [thanksmister/android-mqtt-alarm-panel#43]
Your recent fix for UI issues has improved things but as you can see from the screenshots it’s still an issue.

This shows when entering the setting keypad numbers and also the alarm keypad numbers .

![561b43f8-0d41-4d51-b839-d3eb4d467b8d](https://user-images.githubusercontent.com/190136/44996628-d223f480-afa0-11e8-9d54-6c0264c05984.png)
![2936f6d1-c3b4-4f6d-8204-27b129bbb8dc](https://user-images.githubusercontent.com/190136/44996630-d223f480-afa0-11e8-8665-6ebd625baae2.png)

**Comment by aptonline** [comment]
No they appear perfectly fine. The screenshots are the only UI issues I’ve come across

**Comment by thanksmister** [comment]
Ok, I will try to make the dialogs the same size as the alarm options menu to see if that helps.  Ideally I wanted a layout just for your device but it appears I can't determine the specific DPI (screen density) of your particular model.   I have the resolution but DPI determines the actual layout values and icon sizes. From just resolution alone, your device would be the same as a Pixel 2 XL or a Nexus 10 Tablet.  However, these do not have the same issue as your device.

**Comment by aptonline** [comment]
This isn’t a cut off issue but more a UI inconstancy but would it make sense for the disabled state to show an unlocked padlock as opposed to a locked one?

**Comment by thanksmister** [comment]
Now you are scope creeping.   It might make sense but then I would have to pullout my secret ninja photoshop skills.   I would consider that a feature request :).

**Comment by aptonline** [comment]
No problems.

**Comment by thanksmister** [comment]
Ok, you have your own beta program now.  I added a beta version of the Alarm Control panel with new layouts for 640dpi and 720 dpi devices for you to test.  This way I don't accidentally disrupt those with working layouts.   

Here is the link to join the beta program: https://play.google.com/apps/testing/com.thanksmister.iot.mqtt.alarmpanel.

It may take a while for the beta to be available through Google Play

**Comment by aptonline** [comment]
One out of two ain’t bad.

![43793c76-c06e-4cb1-ac7b-705015054639](https://user-images.githubusercontent.com/190136/44999560-1f5e9100-afb6-11e8-8757-8205ddd32656.png)
![0299347d-db3d-4ff1-8d1a-b5f4114a6deb](https://user-images.githubusercontent.com/190136/44999561-1f5e9100-afb6-11e8-9302-c5e545e18d84.png)

**Comment by thanksmister** [comment]
Oops...

**Comment by aptonline** [comment]
Downloaded and tested, all looking good now. Tested in landscape and portrait. Happy to close this issue.

**Comment by thanksmister** [comment]
Great, yes close the issue and I will roll out the beta after I test this on my own tablets.
