### ISSUE TITLE
Disarmed UI inconsistency

### ISSUE THREAD

**Issue by aptonline** [thanksmister/android-mqtt-alarm-panel#44]
Looking at the main alarm screen the screenshot below shows disarmed but the padlock graphic suggests armed as it’s locked. Would this make more sense to show an unlocked padlock to indicate disarmed?

![6e8d654c-e780-43d5-901a-74c870487f3b](https://user-images.githubusercontent.com/190136/44997603-92acd680-afa7-11e8-92ff-819f55372f9d.png)

**Comment by thanksmister** [comment]
No longer valid.
