### ISSUE TITLE
Modify url and turn on the screen remotly

### ISSUE THREAD

**Issue by dannybcn87** [thanksmister/android-mqtt-alarm-panel#45]
Hi, 

Would be great if it will be possible to modify the url and turn on/off the screen by sending a mqtt message or calling a rest service.
I want to connect the screen to mjpeg stream when my outdoor sensors are triggered (also would be great if the app supports rtsp streams).

Thanks,
Danny

**Comment by thanksmister** [comment]
Please look at the docs on how to wake the screen or change the screen brightness using MQTT or HTTP.  Document reference for commands:  https://github.com/thanksmister/android-mqtt-alarm-panel#mqtt-commands.

**Comment by thanksmister** [comment]
> I want to connect the screen to mjpeg stream when my outdoor sensors are triggered (also would be great if the app supports rtsp streams).

This is a separate feature request.
