### ISSUE TITLE
Add option to rotate or flip image for MJPEG output

### ISSUE THREAD

**Issue by thanksmister** [thanksmister/android-mqtt-alarm-panel#47]
On some older devices the image is rotated or flipped.  It would be nice to have a new camera setting to flip and/or rotate the image.   However, first it needs to be determined if this is just a rotation issue or the image is flipped left/right.

**Comment by fcastroruiz** [comment]
Thanks for create it, i follow issue, im interest in it

**Comment by fcastroruiz** [comment]
I see image cam like this:

![image](https://user-images.githubusercontent.com/34915602/45817074-e0cb1500-bcdd-11e8-9bfe-8c259cd14dab.png)

Thanks

**Comment by thanksmister** [comment]
Thanks

**Comment by fcastroruiz** [comment]
I take photo of app camera of the old tablet:

![image](https://user-images.githubusercontent.com/34915602/45943235-d82c5480-bfe5-11e8-9ce9-db4a4bf3cf5b.png)

I change the hardware of the tablet i switch position of the cameras front and back, i think its posible i do something wrong. but tablet camera app work fine.

I try this night with other MJPEG stream app (IP Webcam) and post results

Thnks for your time

**Comment by thanksmister** [comment]
I am talking about going into the settings of the MQTT Alarm Panel application, then to the Camera settings, then to the Camera Test to see what the picture shows.   So    MQTT Alarm Panel > Settings > Camera Settings > Camera Test.   I want to know if the camera test is showing the wrong image or if its only the MJPEG stream that is showing the wrong image.

**Comment by fcastroruiz** [comment]
The camera test show the correct image

**Comment by fcastroruiz** [comment]
In safari in my iPhone :

With url “192.168.0.158:2971/camera/stream”

Show image flipped 

Sorry for my english, thnks

**Comment by thanksmister** [comment]
Ok, then we will be adding a feature to flip the image soon.   Thanks for the help.

**Comment by fcastroruiz** [comment]
Thnks to you for your time

**Comment by thanksmister** [comment]
Feature added in v0.8.3.beta.9
