### ISSUE TITLE
Disarm from app not working

### ISSUE THREAD

**Issue by Sorhac** [thanksmister/android-mqtt-alarm-panel#48]
I have installed the android app to control the hassio alarm, I configured mqtt and alarm and everything works well except disarming the alarm from the app. It arms home and away, flawlessly, it updates the states when I arm or disarm from hassio. But when I put the code to disarm in the app, it does nothing... Any ideas??

**Comment by thanksmister** [comment]
I am running Home Assistant v0.77.3 with Alarm Panel v0.8.3 build 8 from the Google Play store.  All I did was enter my MQTT broker address and update the alarm code.   When I set the alarm to home or away mode and then disable the alarm using the code, all works as it should.    

Perhaps you have a different MQTT setup or you set a pin code on your alarm?   Have a look at the documentation to compare it to your setup to be sure https://github.com/thanksmister/android-mqtt-alarm-panel.    

I don't think its related to the application.   You can try a fresh install and just change your MQTT broker address, this would rule out any other changes that you may have done.

**Comment by Sorhac** [comment]
I'm using this one: https://community.home-assistant.io/t/yet-another-take-on-an-alarm-system/32386
I've been reading everything and I can't seem to find the solution

**Comment by thanksmister** [comment]
That one is not compatible with the MQTT Manual Control Panel component required used in HASS and it doesn't work with the Alarm Control Panel because whomever built it, did a custom job that does't conform to the way HASS components work.   This is the component you should be using with the Alarm Control Panel application: https://www.home-assistant.io/components/alarm_control_panel.manual_mqtt/ .   Maybe you could post on that thread to see whats the issue, I suspect its expecting a code but the HASS component doesn't expect a code from MQTT.

**Comment by Sorhac** [comment]
Oh... ok. :( do you Knife any workaround to this? Im a bit confused Noé about the pin code ... shouldnt it use the code? Isnt it more secure?

**Comment by thanksmister** [comment]
Yes, you can use the Manual Alarm Control Panel (https://www.home-assistant.io/components/alarm_control_panel.manual_mqtt/) and set the code with that component.  Use the same code (or different if you like) in the Alarm Control Panel Android application.   Take a look at the application setup page for instructions how to configure your HASS configuration.yaml file.   You will probably have to stop using https://community.home-assistant.io/t/yet-another-take-on-an-alarm-system/32386 component as it does not work with the Manual Alarm Control Panel  component in HASS. Instructions for setting up everything here https://github.com/thanksmister/android-mqtt-alarm-panel.

**Comment by Sorhac** [comment]
This is the solution: in the alarm.yaml :
#[OPTIONAL] False by default. if true allows MQTT commands to disarm the alarm without a valid code.
override_code: True 
So it is "now" compatible
