### ISSUE TITLE
Use NFC tag to arm/disarm alarm

### ISSUE THREAD

**Issue by martincollignon** [thanksmister/android-mqtt-alarm-panel#49]
It could be very neat if you could use a NFC tag (or even a phone with NFC) to arm/disarm the alarm, as quite a few Android tablet and phones have NFC capabilities

**Comment by ggoodell2** [comment]
i have a nfc tag next to my front door that arms the alarm when i tap it as i leave. its set up in HA and sets alarmo to armed. i would shy away from having a nfc tag for unarm as that can be a security breach.

**Comment by thanksmister** [comment]
I don’t think we will implement this due to the security with NFC tags, being not that safe.  Perhaps a QRCode would be better?  I’m not convinced NFC is best option.  I am open for a PR if someone wants to implement.
