### ISSUE TITLE
Feature Request: Enter Code to access Home Automation Page

### ISSUE THREAD

**Issue by subaru25rs** [thanksmister/android-mqtt-alarm-panel#52]
If the system is armed (or perhaps have the option to set this for different modes) it would be nice if the Home Automation page needed a code to swipe over to as well. Otherwise (theoretically) a savvy attacker could walk in, swipe over to HASS, and shut it down before the alarm ever went off.

It would be nice to have options so you could choose if you want to have it locked or not during Armed_Home.

**Comment by thanksmister** [comment]
It’s up to you if you want to display your platform page and also if you want to display your alarm control panel in your dashboard.  Additionally you could add a code to your alarm panel component in Home Assistant to avoid unauthorized users.  I think adding a code to the swipe is bad for user experience and onerous for each user.
