### ISSUE TITLE
Disconnected from MQTT server on exit from settings (x86)

### ISSUE THREAD

**Issue by oalbaf** [thanksmister/android-mqtt-alarm-panel#53]
On an Android ARM tablet, everything is fine. Fantastic application! 

But on an Android x86 with Android 5 disconnected from MQTT server on exit from settings. Tablet loses the connection from MQTT server if it changes any option of configuration. Only this is solved by restarting the application. Any solution? Thank!!

**Comment by thanksmister** [comment]
When you exit the settings, the MQTT server is actually started, so it appears to be having issues connecting.  Did you check that you have the correct settings in the MQTT settings, can you post what you have for your MQTT.   As far as Android 5 and x86, I have an old Nexus 7 (2009) tablet that runs the alarm panel application. It doesn't have any specific issues.  My guess its either network related or configuration issue.s

**Comment by oalbaf** [comment]
It does not seem like a configuration problem. If you close the app and return it open connect correctly. Also while running the app if you lose the connection WIFI shows the message of disconnection of the MQTT server, but when recovering the signal disappears and everything works fine.

The problem only appears if we modify the configuration and go back to the main screen. If it's not clear, I can make a video.

-----

No parece un problema de configuración. Si tú cierras la app y volverla abrir conecta correctamente. Además mientras corre la app si pierde la conexión WIFI muestra el mensaje de desconexión del servidor MQTT, pero al recuperar la señal desaparece y funciona todo bien.

El problema solo aparece si modificamos la configuración y retrocedemos a la pantalla principal. Si no ha quedado claro puedo realizar un video.

**Comment by thanksmister** [comment]
I will investigate, it could be some type of race condition.  The mqtt client is stopped whem going to the settings screen and restarted again when going back to the main screen.  It seems to be stalling for you when restarting the mqtt service after the settings.

**Comment by oalbaf** [comment]
>  It seems to be stalling for you when restarting the mqtt service after the settings.

Exactly! Thank you!!

**Comment by thanksmister** [comment]
I could not reproduce this issue.   Without reproduction, I can't address it.
