### ISSUE TITLE
UI out of sync when mqtt server briefly lost

### ISSUE THREAD

**Issue by mvoosten** [thanksmister/android-mqtt-alarm-panel#59]
When the mqtt server is rebooted or otherwise not available, the UI of Alarm panel stays out of sync. Only was is to either restart Alarm panel app, or change the mqtt server adres once and back again. Not really helpfull with in wall panel.

**Comment by thanksmister** [comment]
That's a problem with HASS, you need to retain the last state of the MQTT server somehow in your HASS setup so it survives through restart.   The application subscribes to MQTT, so the MQTT state of the alarm must be sent as a message in order to update the application.

**Comment by mvoosten** [comment]
Using domoticz myself. As i send out a change from the built in alarm panel it sends a status change like with regular usage. But then the MQTT Alarm panel still isn't updated as it should according to your description.

**Comment by thanksmister** [comment]
The MQTT server will reconnect to the MQTT broker if temporarily disconnected.  I recommend you add "retain=true" to your publish message parameters and see if that helps.   The MQTT client will not reach out and get a non-published state when it reconnects, so it sounds as though its up to the MQTT broker to publish the current state on any connection loss.   This doesn't happen on my devices as I have always used the retain flag.
