### ISSUE TITLE
Notification command not working

### ISSUE THREAD

**Issue by mvoosten** [thanksmister/android-mqtt-alarm-panel#60]
Tried TTS.
Works on Galaxy S2 tablet,
Doesn't work on Galaxy S8 phone
Also doesn't work on Galaxy S3 phone.
Also notification command isnt working on any device

**Comment by thanksmister** [comment]
Notification is a bug, but for TTS I wasn't able to reproduce the issue on a Galaxy S5.  I don't have the other physical devices to test.   If you have multiple issues, please file a new issue for each otherwise if this issue is closed it will close all other issues associated with it.

**Comment by thanksmister** [comment]
This should have been fixed in Release v0.8.5.beta.2
