### ISSUE TITLE
Cannot build project on Android Studio 3.2.1

### ISSUE THREAD

**Issue by jrhbcn** [thanksmister/android-mqtt-alarm-panel#61]
Hello,

I am trying to build the project using Android Studio. I downloaded the sources and used the option "import existing project" from a clean install of Android Studio. When building the project I get the error:

```
A problem occurred evaluating project ':app'.
Gradle sync failed: Build Config field cannot have a null parameter
```

And google does not seem to find anything. DO I need to setup specific SDK or gradle versions to built it?

Thanks

**Comment by thanksmister** [comment]
The application uses local.properties for debug mode.  I suspect that this is hanging up your build.  Please remove the following code from the MainActivity.kt file:

` if(BuildConfig.DEBUG) {
            configuration.alarmCode = BuildConfig.ALARM_CODE
            darkSkyOptions.darkSkyKey = BuildConfig.DARK_SKY_KEY
            darkSkyOptions.latitude = BuildConfig.LATITUDE
            darkSkyOptions.longitude = BuildConfig.LONGITUDE
            mqttOptions.setBroker(BuildConfig.BROKER)
            configuration.webUrl = BuildConfig.HASS_URL
            configuration.setMailFrom(BuildConfig.MAIL_FROM)
            configuration.setMailGunApiKey(BuildConfig.MAIL_GUN_KEY)
            configuration.setMailTo(BuildConfig.MAIL_TO)
            configuration.setMailGunUrl(BuildConfig.MAIL_GUN_URL)
            configuration.telegramChatId = BuildConfig.TELEGRAM_CHAT_ID
            configuration.telegramToken = BuildConfig.TELEGRAM_TOKEN
            imageOptions.imageClientId = BuildConfig.IMGUR_CLIENT_ID
            imageOptions.imageSource = BuildConfig.IMGUR_TAG // Imgur tags
            darkSkyOptions.setIsCelsius(true)
            configuration.isFirstTime = false
            configuration.setPhotoScreenSaver(false)
            configuration.setHasCameraCapture(true)
            configuration.setWebModule(true)
            configuration.setShowWeatherModule(true)
            configuration.setTssModule(true)
        }`
