### ISSUE TITLE
Browser should be locked when alarm is active

### ISSUE THREAD

**Issue by adipose** [thanksmister/android-mqtt-alarm-panel#62]
If you point your browser at HA instance, It is possible to switch to the HA interface when the alarm is set.  Ideally, this should be locked (or at least an option), due to the possibility of disarming the alarm from the HA interface.

**Comment by thanksmister** [comment]
I think its up to you to either use a code for the alarm control panel or not use the platform screen if you are concerned about someone disarming the alarm.       Using a code won't change the way the application works, it will just require a code when using the HA alarm control in the HA desktop.

**Comment by adipose** [comment]
I do use a code, but I was able to turn off my siren, for example.  I'll probably just eliminate alarm things from a HADashboard and use that.

Thanks--great app by the way.
