### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by electricJP** [thanksmister/android-mqtt-alarm-panel#70]
Provide language specific main screen. I don't think any setup/settings screens need to be translated but main screen should offer translation.
(i can help with French/French Canada translation)

**Comment by thanksmister** [comment]
There are already translations for Portuguese, Dutch, and Spanish.   If you would like to contribute, there are a few files that need to be translated.  The translation will update the entire application, not just the main screen.  

The first file is the string.xml file, this contains all the text displayed in the UI.  It's in xml format and once translated will be place into the appropriate translation folder:

https://github.com/thanksmister/android-mqtt-alarm-panel/blob/master/app/src/main/res/values/strings.xml

The second part that needs translation is the Google Play Store listing which is in very basic HTML 1.0.  The basic HTML tags must be preserved. There is no file but the text is as follows:

```
A MQTT Alarm Control Panel for Home Assistant and home automation platforms.

<b>MQTT Alarm Control Panel</b>

Reuse and old Android devices as a home alarm control panel that integrates with Home Assistant or any home automation platform that supports MQTT messaging. 

MQTT Alarm Control Panel is an alarm control panel for use with home automation platforms that support MQTT messaging.  The application was originally built for <b>Home Assistant's<b><a href="https://home-assistant.io/components/alarm_control_panel.manual_mqtt/">MQTT Manual Control Panel</a></b>. However, the application can be used with any home automation platform that supports the MQTT messaging protocol such as Jeedom, openHab, or Node-Red.

The alarm control panel acts as an interface for your home alarm system and allows for two way communication using MQTT.  You can set the alarm state to away or home, or disarm the alarm using a code.  Your home automation system controls the sensors or automation that triggers the siren or notifies users of possible intrusion. 

<b>Features</b>
* Stream video, detect motion, detect faces, and read QR Codes.
* Capture and emailing images when the alarm is disabled.
MQTT commands to remotely control the application (speak text, play audio, display notifications, alerts).
* Device sensor data reporting over MQTT (temperature, light, pressure, battery, etc.).
* Day/Night mode themes based on set start and end times.
* Fingerprint unlock support to disable the alarm. (on supported devices).
* Optional screensaver mode using a digital clock or Imgur images.
* Seven day Weather forecast (requires DarkSky api key).
* Home Automation Platform webpage support for viewing home automation dashboards.

The alarm panel is designed to be used as a dedicated device which runs continuously in full-screen mode. The alarm panel is open source and available on GitHub. There is also a version that runs on a Raspberry Pi using Android Things

For the complete setup instructions and additional information,  please visit the <a href="https://thanksmister.com/android-mqtt-alarm-panel/">Project Home Page</a>. 

<a href="https://home-assistant.io">Home Assistant</a>
<a href="https://home-assistant.io/components/alarm_control_panel.manual_mqtt/">Home Assistant's MQTT Manual Alarm Control Panel</a>
<a href="https://thanksmister.com/android-mqtt-alarm-panel/">Project's Home Page</a>
<a href="https://github.com/thanksmister/androidthings-mqtt-alarm-panel">Raspberry Pi Version</a>
Support: mister@thanksmister.com
```

If you are willing to do the translation to French, I will give you contributor credit and assign the ticket to you 👍 .

**Comment by electricJP** [comment]
Ok, I will work on the FR translation next week.

**Comment by electricJP** [comment]
Sorry, I'm late with the FR translation. I got sick and had a big IT issue at work. Half translation is done. I hope to finish it mid next week.

**Comment by thanksmister** [comment]
Thanks, take your time it’s no rush

**Comment by jncanches** [comment]
And here is the french translation for the Google Play Store

[MQTT alarm panel - Google Play Store description - FR.zip](https://github.com/thanksmister/android-mqtt-alarm-panel/files/2657288/MQTT.alarm.panel.-.Google.Play.Store.description.-.FR.zip)

Hope this help.

**Comment by thanksmister** [comment]
Both of you guys are great, thanks for the translation.  @electricJP I had forgot that @jncanches also volunteered to do the translations.  It has been a while and I didn't think you had time to do them.  I will be giving both of you credit for the work.  Thanks!!!

**Comment by thanksmister** [comment]
This is Fr

**Comment by electricJP** [comment]
Hello,

I did a quick review of jncanches translation and fixed a few typos.
[strings.zip](https://github.com/thanksmister/android-mqtt-alarm-panel/files/2657433/strings.zip)

**Comment by jncanches** [comment]
> Hello,
> 
> I did a quick review of jncanches translation and fixed a few typos.
> [strings.zip](https://github.com/thanksmister/android-mqtt-alarm-panel/files/2657433/strings.zip)

Wonderful @electricJP ! Thank you very much :)
Excited about having Control panel in french (more user friendly for my family )
@thanksmister Thank you, your app is very, very good and great !

**Comment by thanksmister** [comment]
Wonderful, thanks!

**Comment by thanksmister** [comment]
Ok, rolled out a new version with the translations.

**Comment by jncanches** [comment]
@thanksmister Sorry, I noticed some little mistakes in the google play store description.
Here is an updated html.
[MQTT alarm panel - Google Play Store description - FR.zip](https://github.com/thanksmister/android-mqtt-alarm-panel/files/2657876/MQTT.alarm.panel.-.Google.Play.Store.description.-.FR.zip)

**Comment by thanksmister** [comment]
Updated!

**Comment by jncanches** [comment]
Moreover, seeing app capture on Google Play Store makes me think that main screen may display "ALARME DESACTIVEE" or "ALARME MODE ABSENT" and not "SYSTEME DESACTIVEE" (which contains a grammatical error) and "SYSTEME MODE ABSENT".
I updated the strings.xml if @electricJP  and you @thanksmister are ok with that
[strings.zip](https://github.com/thanksmister/android-mqtt-alarm-panel/files/2657906/strings.zip)

**Comment by jncanches** [comment]
Damn, I have not attach the right Google Play store description in my previous comment. Really sorry :(
Here is the really updated one 
[MQTT alarm panel - Google Play Store description - FR.zip](https://github.com/thanksmister/android-mqtt-alarm-panel/files/2657926/MQTT.alarm.panel.-.Google.Play.Store.description.-.FR.zip)

**Comment by thanksmister** [comment]
@jncanches  You can't change the strings at this point, that ship has sailed.  I truncated the wording for the alarm modes because they were too long.  If they are incorrect, then just provide the exact strings text because I have already updated an fixed the string resources to be escaped properly.  I can not replace all strings.

**Comment by jncanches** [comment]
@thanksmister ok I will look at it and see if it can be shorter. Which word key espacially must be brief ?

Have you the re-corrected wording for Google Play Store ?

**Comment by thanksmister** [comment]
I am updating Google Play now.   I think it can just be "Arm Away" or "Arm Home" or if needed just "Away" or "Home" for the modes, along with "Disarmed".     I don't know if the documents for the alarm component in HA are in french, but the commands are shown https://www.home-assistant.io/components/alarm_control_panel.manual_mqtt/.

**Comment by thanksmister** [comment]
The play store is once again updated.

**Comment by thanksmister** [comment]
Right now I have these values:

    ```
<string name="text_title_system">SYSTEME</string>
    <string name="text_titled_disarmed">DESACTIVEE</string>
    <string name="text_titled_armed_away">MODE ABSENT</string>
    <string name="text_arm_home">ACTIVER MODE PRESENT</string>
    <string name="text_arm_away">ACTIVER MODE ABSENT</string>
    <string name="text_armed_home">MODE PRESENT</string>
    <string name="text_armed_away">MODE ABSENT</string>
```

**Comment by jncanches** [comment]
I think you can use :

<string name="text_title_system">ALARME</string>
<string name="text_titled_disarmed">DESACTIVEE</string>
<string name="text_titled_armed_away">MODE ABSENT</string>
<string name="text_arm_home">ACTIVER PRESENT</string>
<string name="text_arm_away">ACTIVER ABSENT</string>
<string name="text_armed_home">MODE PRESENT</string>
<string name="text_armed_away">MODE ABSENT</string>
<string name="text_system">ALARME</string>
<string name="text_disarmed">DESACTIVEE</string>

**Comment by thanksmister** [comment]
Thanks, I will try to add this to the next release.
