### ISSUE TITLE
Remotely Accessible Home Automation Dashboard 

### ISSUE THREAD

**Issue by mohitagnihotri** [thanksmister/android-mqtt-alarm-panel#73]
To remotely access the Dashboard, there should be REMOTE URL option in "Browser" along with DASHBOARD ADDRESS.

In Dashboard Address, we can enter local IP address to access dashboard when in local WiFi while in remote URL, we can enter cloud URL
so that if local IP is not reachable then it should redirect to remote URL.

This feature would be beneficial for openHAB users where they can use remote cloud URL like https://demo.openhab.org:8443/start/index  to access remotely.

For HA users, they can use local IP as well as DynamicDNS host name.

WHAT CHANGE NEEDS TO BE DONE:
When user access their Dashboard activity, first ping to local IP, if not reachable/error then redirect to remote URL.

**Comment by thanksmister** [comment]
Interesting, not sure when we might have time to complete this, but we can mark it as a feature request.
