### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by phantomdarkness** [thanksmister/android-mqtt-alarm-panel#8]
The HA version supports a "night mode" but the panel currently doesn't (it just sits in "pending" mode).  Could something be added for this mode?

https://home-assistant.io/components/alarm_control_panel.manual_mqtt/

**Comment by thanksmister** [comment]
I think this over complicates the alarm control panel.  It would have three modes just to activate the system.   Home Assistant isn't the only platform that this is used for.   I am also not sure what benefit night mode offers, couldn't the same be achieved just by making your automations or scripts work based on time of day instead.  Night mode never made much sense to me other than convenience.

**Comment by phantomdarkness** [comment]
Fair enough.  I'll make do with home mode instead.  Thanks!
