### ISSUE TITLE
Portrait mode.

### ISSUE THREAD

**Issue by prigal** [thanksmister/android-mqtt-alarm-panel#9]
Hello,

I'm new to your project, just installed the app last night, but not yet connected to my HA. 
I may have several question, I will try to separate them in different issues :) 

First one, do you plan to do a portrait version ? It will be easier when used on the daily smartphone (not the one that will be plugged into my wall).

Thanks.

**Comment by thanksmister** [comment]
Pierre,

Thanks for the questions. I designed the application to replace dedicated
alarm panels and interface with HASS.  Most alarm systems operate within a
home.

Carrying around the panel in your phone outside the home never seemed
logical to me.  The panel requires a constant connection to the MQTT broker
which is usually behind you're firewall on a local network.

Thanks!

**Comment by thanksmister** [comment]
I think a better solution would be to make a smaller version that only talked to the MQTT service with minimal user interface. I am closing this issue as it's a feature request and not really an issue.

**Comment by prigal** [comment]
Yes it's more a feature request, you're right. 

About carrying around the panel it's more a convenient way of using it while not having a panel on my wall. My mqtt is open outside of my home actually for some testing with tracking, but it's secured over TLS and a letsencrypt certificate + authentication.
