### ISSUE TITLE
Ignore MQTT Issues

### ISSUE THREAD

**Issue by edwork** [thanksmister/android-mqtt-alarm-panel#91]
For various reasons my tablet loses the connection to the MQTT server on occasion. It always reconnects, however sometimes a stack of dialog notifications get thrown warning the user that we have lost connection to the MQTT server. These events are external to the App and I can't mitigate them.

It would be awesome to have a "ignore errors" mode where you don't get a dialog, or instead these get thrown in a more passive manor.

Thanks for the consideration!

**Comment by thanksmister** [comment]
Please provide the application version you are using, its under the settings then the about option.

**Comment by edwork** [comment]
This happens with the latest/all versions. To be clear, this is **not** a bug with the app. With dialog messages (or similar) it requires intervention from me to clear 1 or many of them in a stack - even if the connection is restored. 

Something like a passive status indicator off to the side might solve this.

**Comment by thanksmister** [comment]
I need to be able to reproduce the issue, so I need to know which version of the application you are using.   There was an issue like this reported and fixed many versions ago, so if you can tell me which version you see this, I might be able to verify it.

**Comment by edwork** [comment]
The original issue was with 0.8.1, but I just got home to a message saying "Alarm Disconnected, the network connection is unavailable".

**Comment by thanksmister** [comment]
You're original issues was that you received many stacked dialogs.   Does this still occur on v0.8.6 Beta 1 or are you seeing a single alarm disconnected message?

**Comment by thanksmister** [comment]
The message that you see will disappear if the network is connected again, most likely culprit is your phone is disconnected from the network or for some other network reason it can't reconnect with the server.   The message is valid and it's there most likely because it can't reconnect.  However, if you are seeing multiple stacked dialogs, then sure there is an issue.   I don't receive these messages, not even during a HA restart because the app reconnects back to the MQTT broker.

**Comment by edwork** [comment]
I received a single message, so that seems to be working as intended now.  

However this still requires intervention to press OK when in the background the connection is usually back online. My original intent was to make something more along the lines of a "quiet alert" option that wouldn't require the user to actually press anything.

**Comment by thanksmister** [comment]
Can you confirm the MQTT broker is indeed back online?  The message means that it can not reconnect on its own or its given up on trying.    The user is not required to dismiss this message unless the application cannot reconnect with the MQTT broker.  That is the reason you are seeing this message.  I will look at how this message is generated and dismissed to be sure the logic is correct, but on my HA setup, the application handles the MQTT broker disconnect and connect through HA restarts without issue.

**Comment by edwork** [comment]
Ah, makes sense. I upgraded from 0.8.1 to latest at the same time I filed this issue. More than likely this is no longer an issue.  

This weekend I'll try spinning up a second MQTT instance and see if I can replicate previous issues.

**Comment by thanksmister** [comment]
Thanks, would be great if you could test this.

**Comment by edwork** [comment]
I've not found any issues, we've also survived several unexpected restarts of my primary stack.

I think it's safe to say this was a false alarm. Thanks!

**Comment by thanksmister** [comment]
Awesome!!
