### ISSUE TITLE
First time message is shown everytime the app is reloaded

### ISSUE THREAD

**Issue by Mark-81** [thanksmister/android-mqtt-alarm-panel#94]
I'm using your app on RPiB+ with Android Oreo.
Everytime the app is reloaded it shows the welcome message:

> "Since this is your first time, please setup your device, MQTT server [...]"

But all is already configured! It's just the system that run again the app.

**Comment by Mark-81** [comment]
Before close the issues please wait if users have something else to say...

I downloaded and configured your app also on my Huawei Honor View 10 with Android 9 and the behavior is exactly the same:

1. launch your app: welcome message is shown
2. setup all the MQTT stuff
3. close the app using the "task manager" (sorry I don't know the Android terms for this)
4. launch again your app: message is still there

**Comment by thanksmister** [comment]
Your setup isn't complete unless you also set a default alarm code.  Then the nag message goes away.  Try it and let me know.

**Comment by thanksmister** [comment]
The message says  "Since this is your first time, please setup your device, MQTT server, and alarm information".  So it's not just the MQTT you need to set up.   Hopefully that clears up the confusion.

**Comment by Mark-81** [comment]
Oh yes, I mis-understood the message. To test the app I've used the default code! So it didn't recognize it as a "new code". Hence the incomplete setup.

**Comment by thanksmister** [comment]
I am closing this issue for now.
