### ISSUE TITLE
TTS seems not follow the current language

### ISSUE THREAD

**Issue by Mark-81** [thanksmister/android-mqtt-alarm-panel#95]
RPi3B+ with Android Oreo, English as system language. In the Android TTS settings I downloaded the Italian language and **selected this as default for text-to-speech**. Anyway, when I send a "speak" command the app will try to speak in English, rather than in Italian as expected.

**Comment by thanksmister** [comment]
RPi3B+ is not device I can support or test.  I can not offer you any suggestions to fix your issue.

**Comment by Mark-81** [comment]
I tried on my Huawei Honor View 10 with Android 9 and the behavior is similar.
The default system language is Italian, I downloaded and set Polish as default language for TTS.
"speak" commands still try to talk in Italian (or English, see below). Anyway, they ignore the default language set for TTS.

To be honest, the only difference I can see is on Huawei it seems it can speak correctly in both Italian and English by default and at the same time. Example: "One, two, three. Ciao come stai?" is spoken correctly! For this reason I had to setup a third language to reproduce the issue.

**Comment by thanksmister** [comment]
The application uses Google TTS, its probably something to do with the device or application not receiving the language changes for the device.  However, there is nothing in the application besides initializing the library.    Perhaps try to restart the device or the application.
