### ISSUE TITLE
Stream remote IP camera

### ISSUE THREAD

**Issue by Mark-81** [thanksmister/android-mqtt-alarm-panel#96]
When the alarm is triggered I set up HA to publish the following commands:

- audio: to play a short siren effect
- wake: to turn on the screen
- speak: to say something useful to understand which sensor has triggered
- alert: to write the same info, in case I'm not there to listen

It would be nice if we can also setup a list of connections to IP cameras and have a command to enable the stream to one of this, example:

`{"camera": 1}`

The expected behavior is that when the alarm triggers, HA will publish this command with the index of the most relevant camera to show on your app.

**Comment by thanksmister** [comment]
You would need the MJPEG stream url of the camera, or a link to the still screenshot.  Additionally, you would need a way in the application to display live MJPEG streams.    The application works the other way, it publishes a MJPEG steam to HA or any website or publishes images if the app is disarmed.

**Comment by Mark-81** [comment]
Yep, I'm aware of this. Hence I opened the issue as "feature request" :-)

**Comment by thanksmister** [comment]
Yeah, I am just fleshing out the idea more.   There is already a feature request to support streams in the app, but you've added some nice additional information.
