### ISSUE TITLE
way to instantly trigger (bypassing delay) for some sensors

### ISSUE THREAD

**Issue by aaamoeder** [thanksmister/android-mqtt-alarm-panel#98]
When the alarm is armed I'd like our backdoor sensor to instantly trigger the alarm but when the front door opens I 'd like to have a pending time to enter the code..
any way to accomplish this ?

thanks in advance and thaks A LOT for all the effort you've put in :)

**Comment by thanksmister** [comment]
You can do this in HA with automations, this isn't something the application would be able to handle.  The app isn't aware of your sensors, it just reacts to the MQTT messages sent from HA.  So probably in this case the alarm would be sent to away mode, but you would send an alarm triggered and sound your sirens when someone trips the sensor in your backyard.

**Comment by aaamoeder** [comment]
Will try to get something working ;) thanks for the superfast reply !

**Comment by aaamoeder** [comment]
Just tried, but when I send mqtt messages for "pending" and "triggered" the state in ha doesnt get updated.
Is this because the component doesnt have those seperate states ?

**Comment by thanksmister** [comment]
You want to call the service, not call the MQTT message.  You are in HA, so just talk directly with the service, MQTT is for communicating to components outside of HA.

**Comment by thanksmister** [comment]
Check under the developer tools, first icon, and enter the service alarm_control_panel.alarm_trigger, be aware that if you set a code, you also need this passed into the entity to trigger it.

**Comment by thanksmister** [comment]
<img width="742" alt="Screen Shot 2019-04-28 at 9 34 06 PM" src="https://user-images.githubusercontent.com/142340/56872266-609c2900-69fd-11e9-89ec-9c7dc8ed4f47.png">

**Comment by aaamoeder** [comment]
I can directly call the app panel to trigger through mqtt, but not the HA component..
when I call the trigger service, it starts with the pending time anyway..

**Comment by thanksmister** [comment]
Calling the app with MQTT will not be the solution.  That just round trips back to HA.  There must be a way with the service, let me dig around a bit and get back to you.

**Comment by thanksmister** [comment]
Basically you want two pending times, one for home set to zero, and another for away set to 30 seconds.  Pending mode starts when the HA alarm sets to trigger, so you may have to do a nasty work around.  If someone trips the sensor for the back door, set the alarm mode to home, then call trigger, with the alarm setup for home mode to be 0 pending.  Not ideal, but off the top of my head, that is one solution.

**Comment by thanksmister** [comment]
https://www.home-assistant.io/components/manual_mqtt/ 

Take a look at the  pending_time, delay_time, and trigger_time.  You want a short pending and delay for your home mode.  A long trigger time means how long the siren goes off, how long the alarm is in trigger mode.

**Comment by aaamoeder** [comment]
yeah, figured the same .. seems like an oversight that the HA component doesn't have a straight trigger service call.. will put in a feauture request ;)

**Comment by aaamoeder** [comment]
issue created.
--> https://github.com/home-assistant/home-assistant/issues/23526

**Comment by thanksmister** [comment]
They could use a panic mode, which this feature would allow by going straight to triggered mode.

**Comment by aaamoeder** [comment]
> Basically you want two pending times, one for home set to zero, and another for away set to 30 seconds. Pending mode starts when the HA alarm sets to trigger, so you may have to do a nasty work around. If someone trips the sensor for the back door, set the alarm mode to home, then call trigger, with the alarm setup for home mode to be 0 pending. Not ideal, but off the top of my head, that is one solution.

Won't really work since we use both when one of us is at work while the rest is still asleep .. (wife and I both work shifts..) so we need pending times for both home and away mode

**Comment by thanksmister** [comment]
There is a night mode.  But home mode should have no pending time, you want an alarm to go off Immediately when you are home and a door is opened .  The away mode can have a delay time so you have time to disarm it.  

What I suggest is you have home mode with no pending or delay time and away mode to have pending away time of 30 seconds.  If you set the alarm to away mode and enter through the front door, you have 30 seconds to enter the code. 

However if the back door is ever opened while any alarm mode is set you would have an automation that sets the alarm to home mode first, then trigger mode.  This removes the delay and pending time and the alarm is sent to triggered mode automatically.   

My home and away modes are already set this way, I’m just suggesting a different way to setup your automation to achieve the desired results.  Your back door forces alarm home mode first then triggers it.

**Comment by aaamoeder** [comment]
> There is a night mode. But home mode should have no pending time, you want an alarm to go off Immediately when you are home and a door is opened . The away mode can have a delay time so you have time to disarm it.
> 
> What I suggest is you have home mode with no pending or delay time and away mode to have pending away time of 30 seconds. If you set the alarm to away mode and enter through the front door, you have 30 seconds to enter the code.
> 
> However if the back door is ever opened while any alarm mode is set you would have an automation that sets the alarm to home mode first, then trigger mode. This removes the delay and pending time and the alarm is sent to triggered mode automatically.
> 
> My home and away modes are already set this way, I’m just suggesting a different way to setup your automation to achieve the desired results. Your back door forces alarm home mode first then triggers it.

While this is a very good suggestion.. the android app only works for home and away modes, so I should create the night mode as no delay - instant alarm and use it as inbetween mode before the trigger ?

**Comment by thanksmister** [comment]
I would either setup the night mode just as an in between mode for your back door automation to trigger the alarm instantly order your home mode to be no pending or delay time and use it.  My home mode is already zero delay or pending time because if I’m home I want the alarm to be instant.   However if you don’t want your home mode that way, hack the night mode just to use for your automation.  The app will ignore the night mode being set but will react to the alarm triggered mode, which is what is sent after the pending time has passed if you don’t enter the code to disarm.

**Comment by aaamoeder** [comment]
It works ! thanks for all the help ;)
